import {it,expect} from 'vitest';
import {historySessions} from '../src/history-sessions.mjs';
import {historySessionText,historyPngLayout} from '../src/history-sharing.mjs';
const row=(id)=>({id,time:'2026-10-06T12:00:00Z',operation:`op ${id}`,display:String(id),value:Number(id),note:`nota ${id}`});
const sep={id:'clx',kind:'separator',time:'2026-10-06T12:01:00Z',operation:'CLX'};
it('preserva registros antigos e notas; omite blocos vazios entre CLx',()=>{const history=[row('1'),sep,{...sep,id:'again'},row('2')],before=JSON.stringify(history),groups=historySessions(history);expect(groups).toHaveLength(2);expect(groups[0].closed).toBe(true);expect(groups[1].closed).toBe(false);expect(groups[0].entries[0]).toBe(history[0]);expect(JSON.stringify(history)).toBe(before)});
it('aceita primeiro e último bloco aberto e limite parcial de 100 linhas',()=>{expect(historySessions([])).toEqual([]);expect(historySessions([sep,sep])).toEqual([]);expect(historySessions([row('1')])[0].partial).toBe(false);expect(historySessions(Array.from({length:100},(_,i)=>row(String(i))))[0].partial).toBe(true);expect(historySessions([sep,...Array.from({length:99},(_,i)=>row(String(i)))])[0].partial).toBe(false)});
it('exporta ordem cronológica, todas as notas e última saída',()=>{const session=historySessions([row('1'),row('2'),sep])[0],text=historySessionText(session);expect(text.indexOf('op 1')).toBeLessThan(text.indexOf('op 2'));expect(text).toContain('nota 1');expect(text).toContain('nota 2');expect(text).toContain('Última saída: 2');expect(historySessionText(session,false)).not.toContain('nota');expect(text).toContain('Encerrado por CLx')});
it('pagina sem cortar caracteres, incluindo valores longos e linhas vazias',()=>{const ctx={measureText:text=>({width:text.length})},text='123456789\n\nnota enorme';const pages=historyPngLayout(ctx,text,4,88);expect(pages.length).toBeGreaterThan(1);expect(pages.flat().join('')).toBe(text.replaceAll('\n',''));expect(pages.every(page=>page.length<=2)).toBe(true)});

it('PNG paginado cancela antes de carregar recursos',async()=>{const {createHistoryPngPages}=await import('../src/history-sharing.mjs');const controller=new AbortController();controller.abort();await expect(createHistoryPngPages(historySessions([row('1')])[0],true,{doc:{},signal:controller.signal})).rejects.toMatchObject({name:'AbortError'})});
it('limite de 100 preserva notas remanescentes e marca primeiro bloco parcial',()=>{const original=[row('0'),...Array.from({length:100},(_,i)=>row(String(i+1)))];const kept=original.slice(-100),groups=historySessions(kept);expect(groups[0].partial).toBe(true);expect(groups[0].entries.at(-1).note).toBe('nota 100');expect(groups[0].entries).toHaveLength(100)});

import {presentHistoryItem,presentHistorySession} from '../src/history-presentation.mjs';
it('separador acompanha visor, histórico legado e cópia sem mudar números ou notas',()=>{const item={id:'fmt',time:'2026-10-06T12:00:00Z',operation:'2.5 + 1000',display:'1.002,500',value:1002.5,note:'nota 2.5'};const dot=presentHistoryItem(item,false);expect(dot.display).toBe('1,002.500');expect(dot.operation).toBe('2.5 + 1000');expect(dot.value).toBe(item.value);expect(dot.note).toBe(item.note);const comma=presentHistoryItem({...dot,decimalComma:false},true);expect(comma.display).toBe(item.display);expect(comma.operation).toBe('2,5 + 1000');expect(item.display).toBe('1.002,500');const session=presentHistorySession(historySessions([item])[0],false);expect(historySessionText(session)).toContain('1,002.500');expect(historySessionText(session)).toContain('nota 2.5')});
