import {it,expect} from 'vitest';
import {INITIAL_STATE,pressAction,pressKey,formatDisplay,resolveKeyAction} from '@sagittaryuz/hp12c-core';
import {appendHistory,historyEntry,historySeparator,historyNewestFirst,historyActivity,readHistory,reducePanel} from '../src/hp-panel-state.mjs';
import {createDirectionalDrag} from '../src/directional-drag.mjs';
const initial=()=>structuredClone(INITIAL_STATE),time='2026-10-05T17:00:00.000Z';
const dependencies={initial:INITIAL_STATE,pressAction,pressKey,formatDisplay,displayDefaults:s=>s};
it('registra resultado do motor uma vez, sem reexecutar nem alterar o resultado',()=>{let panel={state:initial(),history:[]};for(const [i,id]of ['2','enter','3','plus'].entries())panel=reducePanel(panel,{type:'key',id,action:resolveKeyAction(id,panel.state.shift),eventId:String(i),time},dependencies);expect(panel.state.x).toBe(5);expect(panel.history).toHaveLength(1);expect(panel.history[0].operation).toBe('2 + 3');expect(appendHistory(panel.history,panel.history[0])).toBe(panel.history)});
it('somente CLX comum separa; limpar memória e reset não inventam linhas',()=>{const state={...initial(),registers:Array(20).fill(8),x:5};const panel={state,history:[{id:'old',time,operation:'2 + 3',display:'5',value:5}]};for(const action of ['clearReg','clearFin','clearStats','backspace'])expect(historyEntry(state,pressAction(state,action),action,{id:action,time,display:'0'})).toBeNull();expect(historyEntry(state,pressAction(state,'clx'),'clx',{id:'clx',time,display:'0'})?.operation).toBe('CLX');const reset=reducePanel(panel,{type:'reset',selected:{values:true},eventId:'reset',time},dependencies);expect(reset.history).toEqual(panel.history);expect(reset.state.registers.every(v=>v===0)).toBe(true);expect(panel.state.registers[0]).toBe(8)});
it('histórico é independente de reset, programa/configuração, e apagar histórico é explícito',()=>{const current={state:initial(),history:[historySeparator({id:'s',time})]};expect(reducePanel(current,{type:'reset',selected:{program:true,settings:true},eventId:'x',time},dependencies).history).toEqual(current.history);expect(reducePanel(current,{type:'clear-history'},dependencies).history).toEqual([])});
it('limite100 inclui separadores, datas são válidas e persistência mantém ambos',()=>{let history=[];for(let i=0;i<105;i++)history=appendHistory(history,historySeparator({id:String(i),time}));expect(history).toHaveLength(100);expect(history[0].id).toBe('5');expect(historySeparator({id:'bad',time:'invalid'})).toBeNull();expect(readHistory({getItem:()=>JSON.stringify(history)})).toEqual(history)});
it('limpar erro, PRGM e STO não inventam operações/separadores',()=>{for(const state of [{...initial(),error:'Error 0'},{...initial(),programMode:true},{...initial(),pendingRegister:'store'}])expect(historyEntry(state,pressAction(state,'clearReg'),'clearReg',{id:'s',time,display:'0'})).toBeNull()});
const point=(y,extra={})=>({pointerId:1,isPrimary:true,button:0,clientX:0,clientY:y,...extra});
it('mouse/touch reconhecem18px lentos, release uma vez e direção',()=>{for(const pointerType of ['mouse','touch'])for(const direction of [1,-1]){const t=createDirectionalDrag(direction);t.down(point(100,{pointerType}));expect(t.up(point(100+17*direction))).toBe(false);t.down(point(100,{pointerType}));expect(t.up(point(100+18*direction))).toBe(true);expect(t.up(point(100+18*direction))).toBe(false)}});
it('cancela multitoque, desvio horizontal, inversão, cancel e pointer secundário',()=>{for(const cancel of [t=>t.other(point(0,{pointerId:2})),t=>t.move(point(60,{clientX:90})),t=>t.move(point(-17)),t=>{t.move(point(80));t.move(point(40))},t=>t.cancel()]){const t=createDirectionalDrag(1);t.down(point(0));cancel(t);expect(t.up(point(100))).toBe(false)}const t=createDirectionalDrag(1);expect(t.down(point(0,{isPrimary:false}))).toBe(false);expect(t.down(point(0,{button:2}))).toBe(false)});
it('ALG registra cálculo concluído no ENTER/igual e não operador pendente',()=>{let p={state:pressAction(initial(),'modeAlg'),history:[]};for(const [i,id]of ['2','plus','3','enter'].entries())p=reducePanel(p,{type:'key',id,action:resolveKeyAction(id,p.state.shift),eventId:String(i),time},dependencies);expect(p.state.x).toBe(5);expect(p.history).toHaveLength(1);expect(p.history[0].operation).toBe('2 + 3')});
it('registra erro real sem resultado reutilizável e sem gerar cálculo ao limpar erro',()=>{const s={...initial(),x:0,y:2};const n=pressAction(s,'divide'),e=historyEntry(s,n,'divide',{id:'err',time,display:formatDisplay(n)});expect(e.kind).toBe('error');expect(e.value).toBeNull();expect(readHistory({getItem:()=>JSON.stringify([e])})).toEqual([e]);expect(historyEntry(n,pressAction(n,'clx'),'clx',{id:'clear',time,display:'0'})?.kind).toBe('separator')});
it('reducer de reset é determinístico em reentrada sem criar separadores',()=>{const c={state:initial(),history:[]},e={type:'reset',selected:{values:true},eventId:'same',time};expect(reducePanel(c,e,dependencies)).toEqual(reducePanel(c,e,dependencies));expect(reducePanel(c,e,dependencies).history).toEqual([])});

it('CLX repetido vazio não duplica; operações/entrada novas permitem nova fronteira',()=>{let p={state:initial(),history:[]};const hit=(id:string,i:number)=>{p=reducePanel(p,{type:'key',id,action:resolveKeyAction(id,p.state.shift),eventId:String(i),time},dependencies)};hit('clx',0);expect(p.history).toHaveLength(0);for(const [i,id]of ['2','enter','3','plus','clx','clx','clx'].entries())hit(id,i+1);expect(p.history.map(e=>e.kind||'result')).toEqual(['result','separator']);hit('7',10);hit('clx',11);expect(p.history).toHaveLength(3);hit('clx',12);expect(p.history).toHaveLength(3);hit('2',13);hit('enter',14);hit('2',15);hit('minus',16);hit('clx',17);expect(p.history.at(-1).kind).toBe('separator');expect(p.history).toHaveLength(5)});
it('ordem visual recente primeiro não modifica100 registros persistidos nem separadores legados',()=>{const rows=Array.from({length:100},(_,i)=>i%10===0?historySeparator({id:String(i),time},'Memória reiniciada'):{id:String(i),time,operation:'soma',display:String(i),value:i});const stored=JSON.stringify(rows),read=readHistory({getItem:()=>stored}),view=historyNewestFirst(read);expect(view[0].id).toBe('99');expect(view.at(-1).id).toBe('0');expect(JSON.stringify(read)).toBe(stored);const newest=appendHistory(read,{id:'100',time,operation:'soma',display:'100',value:100});expect(historyNewestFirst(newest)[0].id).toBe('100');expect(newest).toHaveLength(100);expect(newest[0].id).toBe('1')});
it('reset de valores/programa/configurações mantém histórico; exclusão explícita ainda funciona',()=>{const c={state:{...initial(),x:5},history:[{id:'old',time,operation:'soma',display:'5',value:5}]};for(const selected of [{values:true},{settings:true},{program:true},{values:true,settings:true,program:true}])expect(reducePanel(c,{type:'reset',selected,eventId:'reset',time},dependencies).history).toEqual(c.history);expect(reducePanel(c,{type:'reset',selected:{values:true,history:true},eventId:'reset',time},dependencies).history).toEqual([])});

it('CLX repetido no ALG vazio não duplica fronteira ao cancelar expressão pendente',()=>{let p={state:pressAction(initial(),'modeAlg'),history:[]};for(const [i,id]of ['2','plus','0','clx','clx','clx'].entries())p=reducePanel(p,{type:'key',id,action:resolveKeyAction(id,p.state.shift),eventId:String(i),time},dependencies);expect(p.history).toHaveLength(1);expect(p.history[0].operation).toBe('CLX');expect(p.state.algOperators).toEqual([])});

it('gesto rápido12px em30ms abre, lento12px ou jitter8px não',()=>{for(const [dy,ms,want]of [[12,30,true],[12,200,false],[8,10,false]]){const t=createDirectionalDrag(1);t.down({...point(0),timeStamp:0});expect(t.up({...point(dy),timeStamp:ms})).toBe(want)}});

it('flick após segurar usa velocidade recente e acompanha pequena inversão',()=>{const t=createDirectionalDrag(1);t.down({...point(0),timeStamp:0});t.move({...point(6),timeStamp:500});t.move({...point(18),timeStamp:520});expect(t.up({...point(18),timeStamp:525})).toBe(true);t.down({...point(0),timeStamp:0});t.move({...point(30),timeStamp:500});t.move({...point(12),timeStamp:550});expect(t.distance()).toBe(12);expect(t.up({...point(12),timeStamp:650})).toBe(false)});

it('atividade explícita permite tecla0 sem valor novo; CLX repetido preserva uma fronteira e contas',()=>{let p:any={state:initial(),history:[],historyActive:false};let n=0;const hit=(id:string)=>p=reducePanel(p,{type:'key',id,action:resolveKeyAction(id,p.state.shift),eventId:String(n++),time},dependencies);hit('0');expect(p.historyActive).toBe(true);hit('clx');expect(p.history).toHaveLength(1);for(let i=0;i<8;i++)hit('clx');expect(p.history).toHaveLength(1);expect(p.historyActive).toBe(false);hit('2');hit('enter');hit('3');hit('plus');hit('clx');const saved=JSON.stringify(p.history);for(let i=0;i<8;i++)hit('clx');expect(JSON.stringify(p.history)).toBe(saved);expect(p.history).toHaveLength(3)});
it('atividade persistida prevalece sobre X, é compatível com legado e exclusão explícita',()=>{const state={...initial(),x:5},rows=[historySeparator({id:'s',time})];expect(historyActivity(state,rows,'false')).toBe(false);expect(historyActivity(initial(),rows,'true')).toBe(true);expect(historyActivity(initial(),rows)).toBe(false);const c={state,history:rows,historyActive:false};expect(reducePanel(c,{type:'key',id:'clx',action:'clx',eventId:'repeat',time},dependencies).history).toEqual(rows);expect(reducePanel(c,{type:'clear-history'},dependencies).historyActive).toBe(false)});
it('tolera diagonal vertical e volta cancelada sem flick ou tecla',()=>{const t=createDirectionalDrag(1);t.down({...point(0),timeStamp:0});t.move({...point(20,{clientX:18}),timeStamp:30});expect(t.up({...point(20,{clientX:18}),timeStamp:35})).toBe(true);t.down({...point(0),timeStamp:0});t.move({...point(35),timeStamp:30});t.move({...point(8),timeStamp:60});expect(t.up({...point(30),timeStamp:70})).toBe(false)});
it('restaurar legado usa o estado restaurado para atividade; Backspace físico conta sem resultado',()=>{const rows=[historySeparator({id:'s',time})];let p:any=reducePanel({state:{...initial(),x:5},history:rows,historyActive:true},{type:'restore-history',history:rows,state:initial()},dependencies);expect(p.state.x).toBe(0);expect(p.historyActive).toBe(false);p=reducePanel(p,{type:'action',action:'backspace',physical:true,eventId:'back',time},dependencies);expect(p.historyActive).toBe(true);p=reducePanel(p,{type:'key',id:'clx',action:'clx',eventId:'clear',time},dependencies);expect(p.history).toHaveLength(2);expect(p.historyActive).toBe(false)});
it('painel permite voltar em direção oposta durante o mesmo arrasto e decide só ao soltar',()=>{const t=createDirectionalDrag(-1,true);t.down({...point(100),timeStamp:0});t.move({...point(80),timeStamp:50});expect(t.offset()).toBe(20);t.move({...point(100),timeStamp:70});expect(t.active()).toBe(true);expect(t.offset()).toBe(0);t.move({...point(140),timeStamp:100});expect(t.active()).toBe(true);expect(t.offset()).toBe(-40);expect(t.up({...point(140),timeStamp:105})).toBe(false)});
