import {it,expect} from 'vitest';
import {attachSurfacePull} from '../src/surface-pull.mjs';
function setup(scroll=false,options={}){const win=new EventTarget(),doc:any=new EventTarget(),root:any=new EventTarget(),outside={closest:()=>null},scroller={scrollTop:0};doc.defaultView=win;root.ownerDocument=doc;root.dataset={};root.contains=(target:any)=>target===root;root.closest=(sel:string)=>sel==='.calculator'?root:scroll&&sel==='.body'?scroller:null;let calls=0;const cleanup=attachSurfacePull(root,{onPull:()=>calls++,scrollSelector:scroll?'.body':undefined,...options});const fire=(type:string,props:any={},target:any=win)=>{const e=new Event(type,{cancelable:true});const {target:ignored,...values}=props;Object.assign(e,{pointerId:1,button:0,isPrimary:true,clientX:0,clientY:0,...values});Object.defineProperty(e,'target',{value:props.target||root});target.dispatchEvent(e);return e};return{win,root,doc,scroller,outside,fire,cleanup,calls:()=>calls};}
it('opens once from an interactive surface and consumes only the compatible click',()=>{const h=setup();h.fire('pointerdown');h.fire('pointerup',{clientY:80});expect(h.calls()).toBe(1);expect(h.fire('click',{detail:1}).defaultPrevented).toBe(true);expect(h.fire('click',{detail:0}).defaultPrevented).toBe(false);h.cleanup()});
for(const kind of ['pointercancel','blur','resize','pagehide','visibilitychange'])it('cancels '+kind,()=>{const h=setup();h.fire('pointerdown');if(kind==='visibilitychange'){h.doc.hidden=true;h.fire(kind,{},h.doc)}else {if(kind==='resize')(h.win as any).innerHeight=800;h.fire(kind);}h.fire('pointerup',{clientY:80});expect(h.calls()).toBe(0);h.cleanup()});
it('ignores outside gestures and rejects multitouch',()=>{const h=setup();h.fire('pointerdown',{target:h.outside});h.fire('pointerup',{clientY:80});expect(h.calls()).toBe(0);h.fire('pointerdown');h.fire('pointerdown',{pointerId:2,isPrimary:false});h.fire('pointerup',{clientY:80});expect(h.calls()).toBe(0);h.cleanup()});
it('allows menu pulling only at the initial scroll boundary',()=>{const h=setup(true);h.scroller.scrollTop=10;h.fire('pointerdown');h.fire('pointerup',{clientY:80});expect(h.calls()).toBe(0);h.scroller.scrollTop=0;h.fire('pointerdown');h.fire('pointerup',{clientY:80});expect(h.calls()).toBe(1);h.cleanup()});
it('reserves downward touch at the menu top and leaves upward scrolling free',()=>{const h=setup(true);h.fire('touchstart',{touches:[{identifier:1,clientX:0,clientY:0}]},h.root);expect(h.fire('touchmove',{touches:[{identifier:1,clientX:0,clientY:-20}]},h.root).defaultPrevented).toBe(false);expect(h.fire('touchmove',{touches:[{identifier:1,clientX:0,clientY:20}]},h.root).defaultPrevented).toBe(true);h.cleanup();expect(h.fire('touchmove',{touches:[{identifier:1,clientX:0,clientY:20}]},h.root).defaultPrevented).toBe(false)});

it('ignora resize espúrio, mas cancela perda de captura',()=>{const h=setup();h.fire('pointerdown');h.fire('resize');h.fire('pointerup',{clientY:20});expect(h.calls()).toBe(1);h.fire('pointerdown');h.fire('lostpointercapture');h.fire('pointerup',{clientY:30});expect(h.calls()).toBe(1);h.cleanup()});

it('lista interna nunca transfere gesto ao painel, inclusive nos dois limites',()=>{const h=setup(true,{ignoreSelector:'.body',direction:-1});for(const top of[0,100]){h.scroller.scrollTop=top;h.fire('pointerdown');h.fire('pointerup',{clientY:-40});expect(h.calls()).toBe(0)}h.root.closest=()=>null;h.fire('pointerdown');h.fire('pointerup',{clientY:-20});expect(h.calls()).toBe(1);h.cleanup()});
it('após assumir arrasto, voltar à origem continua ativo até soltar',()=>{const samples:any[]=[];const h=setup(false,{direction:-1,freeMotion:true,onProgress:(d:number,phase:any)=>samples.push([d,phase.active])});h.fire('pointerdown');h.fire('pointermove',{clientY:-20});h.fire('pointermove',{clientY:0});h.fire('pointermove',{clientY:20});expect(samples.slice(0,3)).toEqual([[20,true],[0,true],[-20,true]]);h.fire('pointerup',{clientY:20});expect(samples.at(-1)).toEqual([0,false]);expect(h.calls()).toBe(0);h.cleanup()});
