export type Shift = "f" | "g" | null;
export type KeyDefinition = { id: string; label: string; f: string; g: string; shortcut: string; action: string; fAction: string; gAction: string; tone?: string; row: number; col: number; printF?: boolean; help?: string };
const key = (id:string,label:string,f:string,g:string,shortcut:string,action:string,fAction:string,gAction:string,row:number,col:number,extra:Partial<KeyDefinition> = {}):KeyDefinition => ({id,label,f,g,shortcut,action,fAction,gAction,row,col,...extra});
export const KEY_DEFINITIONS: KeyDefinition[] = [
  key('sin','SIN','','','F7','sin','','',0,-1),
  key('cos','COS','','','F8','cos','','',1,-1),
  key('tan','TAN','','','F9','tan','','',2,-1),
  key('n','n','AMORT','12×','N','n','amortize','12x',0,0),
  key('i','i','INT','12÷','I','i','interest','12div',0,1),
  key('pv','PV','NPV','CF₀','V','pv','npv','cf0',0,2),
  key('pmt','PMT','RND','CFⱼ','M','pmt','round','cfj',0,3),
  key('fv','FV','IRR','Nⱼ','F','fv','irr','nj',0,4),
  key('chs','CHS','RPN','DATE','C','chs','modeRpn','date',0,5),
  key('7','7','7 casas','BEG','7','7','fixed7','begin',0,6,{printF:false}),
  key('8','8','8 casas','END','8','8','fixed8','end',0,7,{printF:false}),
  key('9','9','9 casas','MEM','9','9','fixed9','memory',0,8,{printF:false}),
  key('divide','÷','','←','/','divide','','backspace',0,9),
  key('pow','yˣ','PRICE','√x','Y','pow','bondPrice','sqrt',1,0),
  key('reciprocal','1/x','YTM','eˣ','R','reciprocal','bondYield','exp',1,1),
  key('pctT','%T','SL','LN','T','pctT','deprSL','ln',1,2),
  key('deltaPct','Δ%','SOYD','FRAC','D','deltaPct','deprSOYD','frac',1,3),
  key('pct','%','DB','INTG','%','pct','deprDB','intg',1,4),
  key('eex','EEX','ALG','ΔDYS','E','eex','modeAlg','days',1,5),
  key('4','4','4 casas','D.MY','4','4','fixed4','dmy',1,6,{printF:false}),
  key('5','5','5 casas','M.DY','5','5','fixed5','mdy',1,7,{printF:false}),
  key('6','6','6 casas','x̄w','6','6','fixed6','weightedMean',1,8,{printF:false}),
  key('multiply','×','','x²','*','multiply','','square',1,9),
  key('rs','R/S','P/R','PSE','F5','runStop','program','pause',2,0),
  key('sst','SST','CLEAR Σ','BST','F6','step','clearStats','backStep',2,1),
  key('roll','R↓','CLEAR PRGM','GTO','ArrowDown','roll','clearProgram','goto',2,2),
  key('swap','x↔y','CLEAR FIN','x≤y','Tab','swap','clearFin','testLe',2,3),
  key('clx','CLx','CLEAR REG','x=0','Delete','clx','clearReg','testZero',2,4),
  key('enter','ENTER','PREFIX','=','Enter','enter','prefix','equals',2,5),
  key('1','1','1 casa','x̂,r','1','1','fixed1','estimateX',2,6,{printF:false}),
  key('2','2','2 casas','ŷ,r','2','2','fixed2','estimateY',2,7,{printF:false}),
  key('3','3','3 casas','n!','3','3','fixed3','factorial',2,8,{printF:false}),
  key('minus','−','','UNDO','-','minus','','undo',2,9),
  key('on','ON','OFF','','Escape','on','off','',3,0,{tone:'power'}),
  key('f','f','','','F1','shiftF','','',3,1,{tone:'shift-f'}),
  key('g','g','','','F2','shiftG','','',3,2,{tone:'shift-g'}),
  key('sto','STO','','(','S','store','','parenOpen',3,3,{tone:'utility'}),
  key('rcl','RCL','',')','L','recall','','parenClose',3,4,{tone:'utility'}),
  key('0','0','0 casas','x̄','0','0','fixed0','mean',3,6,{printF:false}),
  key('decimal','.','Notação científica','s','.','decimal','scientific','stddev',3,7,{printF:false}),
  key('sigma','Σ+','','Σ−','A','sigmaPlus','','sigmaMinus',3,8),
  key('plus','+','','LST x','+','plus','','lastX',3,9),
];
export const KEY_BY_ID = Object.fromEntries(KEY_DEFINITIONS.map(key=>[key.id,key])) as Record<string,KeyDefinition>;
export function resolveKeyAction(id:string,shift:Shift):string { const key=KEY_BY_ID[id]; return shift==='f' ? key?.fAction || key?.action || id : shift==='g' ? key?.gAction || key?.action || id : key?.action || id; }
