const {chromium,webkit}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const results=[];
for(const [name,engine,opts]of [['chromium',chromium,{executablePath:'/usr/bin/chromium',args:['--no-sandbox','--ignore-certificate-errors']}],['webkit',webkit,{}]]){
 const b=await engine.launch({headless:true,...opts});const c=await b.newContext({ignoreHTTPSErrors:true,deviceScaleFactor:3,hasTouch:true});
 const measure=page=>page.evaluate(()=>{const rect=s=>{const r=document.querySelector(s).getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height,right:r.right,bottom:r.bottom}};return {model:rect('.model-name'),brand:rect('.brand'),inner:rect('.lcd-face'),lcd:rect('.lcd'),maker:rect('.maker-strip'),keys:[...document.querySelectorAll('.key')].map(e=>{const r=e.getBoundingClientRect();return [e.className,r.x,r.y,r.width,r.height]}),frame:rect('.keyboard-frame'),panel:rect('.keyboard-panel')}});
 for(const viewport of [{width:402,height:874},{width:320,height:450},{width:874,height:402},{width:1280,height:720},{width:667,height:375}]){
 const p=await c.newPage(),baseline=await c.newPage();await p.addInitScript(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:()=>Promise.resolve()}}));
 await p.setViewportSize(viewport);await baseline.setViewportSize(viewport);await Promise.all([p.goto('http://127.0.0.1:5180'),baseline.goto('http://127.0.0.1:5181')]);await Promise.all([p.evaluate(()=>document.fonts.ready),baseline.evaluate(()=>document.fonts.ready)]);await p.waitForTimeout(150);
 const a=await measure(p),before=await measure(baseline),errors={left:a.model.x-a.inner.x,right:a.brand.right-a.inner.right};if(viewport.width<viewport.height)assert.ok(Math.abs(errors.left)<.2&&Math.abs(errors.right)<.2,JSON.stringify({name,viewport,a,errors}));else{assert.deepEqual(a.model,before.model);assert.deepEqual(a.brand,before.brand);}
 for(const part of ['model','brand'])for(const dimension of ['y','width','height'])assert.equal(a[part][dimension],before[part][dimension]);for(const part of ['lcd','inner','keys','frame','panel'])assert.deepEqual(a[part],before[part]);
 const overlaps=(r,t)=>r.x<t.right&&r.right>t.x&&r.y<t.bottom&&r.bottom>t.y;const overlap={modelLCD:overlaps(a.model,a.lcd),brandLCD:overlaps(a.brand,a.lcd)};assert.equal(overlap.modelLCD,false);assert.equal(overlap.brandLCD,false);
 await p.locator('.lcd').evaluate(el=>el.dispatchEvent(new MouseEvent('click',{bubbles:true,detail:0})));await p.locator('.lcd-copy-success').waitFor();const s=await p.locator('.lcd-copy-success').boundingBox();if(viewport.width<viewport.height)assert.ok(Math.abs(s.x+s.width/2-(a.model.right+a.brand.x)/2)<.2);
 await p.screenshot({path:new URL(`${name}-${viewport.width}.png`,import.meta.url).pathname});results.push({engine:name,viewport,errors,geometryPreserved:true,overlap,measurements:a});await p.close();await baseline.close();
 }
 const rotating=await c.newPage();await rotating.setViewportSize({width:402,height:874});await rotating.goto('http://127.0.0.1:5180');await rotating.addScriptTag({content:"Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:()=>Promise.resolve()}})"});
 await rotating.locator('.lcd').tap();await rotating.locator('.lcd-copy-success').waitFor();await rotating.setViewportSize({width:874,height:402});await rotating.waitForTimeout(150);let rotated=await measure(rotating);assert.ok(rotated.model.right<rotated.lcd.x);assert.ok(rotated.brand.x>rotated.lcd.right);assert.ok((await rotating.locator('.lcd-transfer-status').boundingBox()).y>300);
 await rotating.setViewportSize({width:402,height:874});await rotating.waitForFunction(()=>{const a=document.querySelector('.model-name').getBoundingClientRect(),b=document.querySelector('.brand').getBoundingClientRect(),r=document.querySelector('.lcd-face').getBoundingClientRect();return Math.abs(a.left-r.left)<.2&&Math.abs(b.right-r.right)<.2});rotated=await measure(rotating);assert.equal(rotated.model.x,rotated.inner.x);assert.equal(rotated.brand.right,rotated.inner.right);const copy=await rotating.locator('.lcd-copy-success').boundingBox();assert.ok(Math.abs(copy.x+copy.width/2-(rotated.model.right+rotated.brand.x)/2)<.2);await rotating.close();results.push({engine:name,test:'live rotation restores safe landscape and exact portrait alignment, existing toast remains correctly positioned',passed:true});
  await b.close();
}
await fs.writeFile(new URL('measurements.json',import.meta.url),JSON.stringify(results,null,2));console.log(JSON.stringify(results.map(({engine,viewport,errors,geometryPreserved,overlap})=>({engine,viewport,errors,geometryPreserved,overlap})),null,2));
