const {chromium,webkit}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const results=[];
for(const [name,engine,options]of [['chromium',chromium,{executablePath:'/usr/bin/chromium',args:['--no-sandbox']}],['webkit',webkit,{}]]){
 const browser=await engine.launch({headless:true,...options});
 for(const [viewport,safe]of [[{width:402,height:874},0],[{width:402,height:874},34],[{width:320,height:450},0],[{width:874,height:402},0],[{width:1280,height:720},0]]){
 const context=await browser.newContext({viewport,deviceScaleFactor:3,hasTouch:true});if(safe)await context.addInitScript(s=>{const observer=new MutationObserver(()=>{if(!document.head)return;observer.disconnect();const style=document.createElement('style');style.textContent='.calculator{--portrait-safe-bottom:'+s+'px!important}';document.head.appendChild(style)});observer.observe(document,{childList:true,subtree:true})},safe);const page=await context.newPage(),baseline=await context.newPage();await Promise.all([page.goto('http://127.0.0.1:5180'),baseline.goto('http://127.0.0.1:5181')]);await Promise.all([page.evaluate(()=>document.fonts.ready),baseline.evaluate(()=>document.fonts.ready)]);
 await page.waitForTimeout(200);await baseline.waitForTimeout(200);
 const measure=p=>p.evaluate(()=>{const rect=s=>{const el=document.querySelector(s);if(!el)return null;const r=el.getBoundingClientRect();return {left:r.left,right:r.right,top:r.top,bottom:r.bottom,width:r.width,height:r.height}};return {keys:[...document.querySelectorAll('.key')].map(e=>{const r=e.getBoundingClientRect();return [e.className,r.x,r.y,r.width,r.height]}),lcd:rect('.lcd'),inner:rect('.lcd-face'),model:rect('.model-name'),brand:rect('.brand'),maker:rect('.maker-name'),frame:rect('.portrait-footer-frame'),makerFont:getComputedStyle(document.querySelector('.maker-name')).font,fontRadius:document.querySelector('.portrait-footer-frame')?getComputedStyle(document.querySelector('.portrait-footer-frame')).borderBottomLeftRadius:null,pointerEvents:document.querySelector('.portrait-footer-frame')?getComputedStyle(document.querySelector('.portrait-footer-frame')).pointerEvents:null}});
 const a=await measure(page),b=await measure(baseline);assert.deepEqual(a.keys,b.keys);assert.deepEqual(a.lcd,b.lcd);assert.deepEqual(a.inner,b.inner);assert.equal(a.makerFont,b.makerFont);assert.equal(a.maker.width,b.maker.width);assert.equal(a.maker.height,b.maker.height);for(const part of ['model','brand'])for(const dimension of ['top','height','width'])assert.equal(a[part][dimension],b[part][dimension]);
 if(viewport.height>viewport.width){
 assert.equal(a.model.left,a.inner.left);assert.equal(a.brand.right,a.inner.right);assert.equal(a.fontRadius,'32px');assert.equal(viewport.height-a.frame.bottom,10);assert.equal(viewport.height-a.maker.bottom,Math.max(10,safe+6));assert.equal(a.pointerEvents,'none');
 assert.ok(Math.max(...a.keys.filter(r=>r[3]>0).map(r=>r[2]+r[4]))<a.frame.top);assert.ok(Math.max(...a.keys.filter(r=>r[3]>0).map(r=>r[2]+r[4]))<a.maker.top);
 }else{assert.deepEqual(a.model,b.model);assert.deepEqual(a.brand,b.brand);assert.deepEqual(a.maker,b.maker);assert.deepEqual(await page.screenshot(),await baseline.screenshot());}
 await page.screenshot({path:new URL(`${name}-${viewport.width}-safe${safe}.png`,import.meta.url).pathname});results.push({engine:name,viewport,safeAreaSimulation:safe,passed:true,measurements:a});await context.close();
 }await browser.close();
}
await fs.writeFile(new URL('visual-results.json',import.meta.url),JSON.stringify(results,null,2));console.log(JSON.stringify(results.map(({engine,viewport,safeAreaSimulation,passed})=>({engine,viewport,safeAreaSimulation,passed})),null,2));
