import {chromium,webkit} from '/tmp/hp12c-browser-tools/node_modules/playwright/index.mjs';import assert from 'node:assert/strict';import fs from 'node:fs/promises';const rows=[];
for(const [name,engine,opts]of [['chromium',chromium,{executablePath:'/usr/bin/chromium',args:['--no-sandbox']}],['webkit',webkit,{}]]){
 const b=await engine.launch({headless:true,...opts});for(const [w,h,safe=0]of JSON.parse(process.env.QA_CASES||'[[402,874],[375,812],[430,932],[320,450],[320,340],[768,1024],[874,402],[1280,720]]'))for(const dpr of [1,3]){
 const c=await b.newContext({viewport:{width:w,height:h},deviceScaleFactor:dpr});if(safe)await c.addInitScript(s=>{const observer=new MutationObserver(()=>{if(!document.head)return;observer.disconnect();const style=document.createElement('style');style.textContent='.calculator{--portrait-safe-bottom:'+s+'px!important}';document.head.appendChild(style)});observer.observe(document,{childList:true,subtree:true})},safe);const p=await c.newPage(),before=await c.newPage();await Promise.all([p.goto('http://127.0.0.1:5198'),before.goto('http://127.0.0.1:5197')]);await Promise.all([p.evaluate(()=>document.fonts.ready),before.evaluate(()=>document.fonts.ready)]);await p.waitForTimeout(200);await before.waitForTimeout(200);
 const measure=()=>{const rect=e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height,right:r.right,bottom:r.bottom}};const q=s=>rect(document.querySelector(s)),lcd=document.querySelector('.lcd'),rim=getComputedStyle(lcd,'::before'),lr=q('.lcd'),rh=parseFloat(rim.height)+(rim.boxSizing==='border-box'?0:parseFloat(rim.borderTopWidth)+parseFloat(rim.borderBottomWidth)),rt=lr.y+(lr.height-rh)/2;const calc=document.querySelector('.calculator'),frame=document.querySelector('.portrait-footer-frame');return {keys:[...document.querySelectorAll('.key')].map(e=>({name:e.className,rect:rect(e),font:getComputedStyle(e).font})),title:q('.model-name'),brand:q('.brand'),maker:q('.maker-name'),lcd:lr,rim:{top:rt,bottom:rt+rh,height:rh},crossbar:q('.keyboard-crossbar'),frame:q('.portrait-footer-frame'),outer:getComputedStyle(frame).borderBottomLeftRadius,inner:getComputedStyle(frame,'::before').borderBottomLeftRadius,offset:Number(calc.dataset.lcdBalanceOffset||0),spread:Number(calc.dataset.keyboardDownwardSpread),paint:getComputedStyle(document.querySelector('.silver-panel')).backgroundImage};};
 const a=await p.evaluate(measure),o=await before.evaluate(measure);for(const k of ['title','brand','maker','crossbar'])assert.deepEqual(a[k],o[k],k);assert.ok(a.paint.includes('metal-grain.svg'));const portrait=h>w;
 for(let i=0;i<a.keys.length;i++){const x=a.keys[i],old=o.keys[i];assert.equal(x.font,old.font);assert.ok(Math.abs(x.rect.width-old.rect.width)<.01);assert.ok(Math.abs(x.rect.x-old.rect.x)<.01);if(!portrait)assert.deepEqual(x,old);else if(!x.name.includes('key-enter'))assert.ok(Math.abs(x.rect.height-old.rect.height)<.01);}
 if(portrait){assert.equal(a.outer,'44px');assert.equal(a.inner,'34px');assert.deepEqual(a.frame,o.frame);assert.ok(a.spread>=o.spread);assert.ok(a.spread<=40);assert.ok(a.spread-o.spread<=10);const ordinary=o.keys.filter(x=>!x.name.includes('key-enter')&&x.rect.width>0),tops=[...new Set(ordinary.map(x=>x.rect.y))].sort((x,y)=>x-y),extra=a.spread-o.spread;
 for(const old of ordinary){const x=a.keys.find(x=>x.name===old.name);assert.ok(Math.abs(x.rect.y-old.rect.y-tops.indexOf(old.rect.y)*extra/6)<.05)}
 const enter=a.keys.find(x=>x.name.includes('key-enter')).rect,one=a.keys.find(x=>x.name.includes('key-1 ')).rect,zero=a.keys.find(x=>x.name.includes('key-0 ')).rect;assert.ok(Math.abs(enter.y-one.y)<.05);assert.ok(Math.abs(enter.bottom-zero.bottom)<.05);const topGap=a.rim.top-a.brand.bottom,bottomGap=a.crossbar.y-a.rim.bottom;assert.ok(topGap>=0&&bottomGap>=1.96);if(a.offset>0)assert.ok(Math.abs(topGap-bottomGap)<.05,JSON.stringify({name,w,h,dpr,topGap,bottomGap,offset:a.offset}));a.gaps={topGap,bottomGap};assert.ok(Math.abs(a.lcd.y-o.lcd.y-a.offset)<.05);assert.ok(Math.abs(a.lcd.height-o.lcd.height)<.01);const bottom=Math.max(...a.keys.filter(x=>x.rect.width>0).map(x=>x.rect.bottom));assert.ok(a.maker.y-bottom>=9.96);a.actualExtra=extra;
 }else assert.deepEqual(a.lcd,o.lcd);
 const file=`${name}-${w}x${h}-safe${safe}-dpr${dpr}.png`;await p.screenshot({path:new URL(file,import.meta.url).pathname});rows.push({engine:name,width:w,height:h,dpr,safe,portrait,measurements:a,baseline:o,passed:true,file});await c.close();}await b.close();}
await fs.writeFile(new URL(process.env.QA_OUTPUT||'geometry-results.json',import.meta.url),JSON.stringify(rows,null,2));console.log('32 geometry/render cases passed');
