import {chromium,webkit} from '/tmp/hp12c-browser-tools/node_modules/playwright/index.mjs';import assert from 'node:assert/strict';import fs from 'node:fs/promises';const results=[];
for(const [name,engine,opts]of [['chromium',chromium,{executablePath:'/usr/bin/chromium',args:['--no-sandbox']}],['webkit',webkit,{}]]){
 const browser=await engine.launch({headless:true,...opts});const c=await browser.newContext({viewport:{width:402,height:874},hasTouch:true});const p=await c.newPage();const errors=[];p.on('pageerror',e=>errors.push(String(e)));await p.goto('http://127.0.0.1:5198');await p.waitForFunction(()=>document.querySelector('.calculator').dataset.keyboardDownwardSpread!==undefined);await p.evaluate(()=>document.fonts.ready);
 for(const id of ['2','enter','3','plus'])await p.locator('.key-'+id).tap();await p.waitForTimeout(200);assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('hp12c-history-v1')).length),1);assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('hp12c-state')).x),5);
 const drag=async(selector,dy,dx=0)=>{const r=await p.locator(selector).boundingBox();const x=r.x+r.width/2,y=r.y+10;await p.mouse.move(x,y);await p.mouse.down();await p.mouse.move(x+dx,y+dy,{steps:8});await p.mouse.up()};
 // Cancellation and normal button presses must never open the sheet.
 await p.mouse.move(201,10);await p.mouse.down();await p.locator('.silver-panel').evaluate(el=>el.dispatchEvent(new PointerEvent('pointercancel',{bubbles:true,pointerId:1})));await p.mouse.move(201,100);await p.mouse.up();assert.equal(await p.locator('.history-board').count(),0);
 await drag('.silver-panel',55);assert.equal(await p.locator('.history-board').count(),0);await drag('.silver-panel',80,30);assert.equal(await p.locator('.history-board').count(),0);await drag('.silver-panel',80);await p.locator('.history-board[open]').waitFor();assert.equal(await p.locator('.history-board li').count(),1);assert.equal(await p.locator('.history-board strong').textContent(),'= 5,0000000');assert.equal(await p.locator('.key-2').evaluate(e=>e.closest('.keys').inert),true);await drag('.history-board-handle',-80);await p.locator('.history-board').waitFor({state:'detached'});
 await p.locator('.key-f').tap();await p.locator('.key-clx').tap();await p.waitForTimeout(200);const list=await p.evaluate(()=>JSON.parse(localStorage.getItem('hp12c-history-v1')));assert.equal(list.length,2);assert.equal(list[1].kind,'separator');await p.locator('.key-clx').tap();await p.waitForTimeout(200);assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('hp12c-history-v1')).length),2);
 await p.locator('.brand').tap();await p.getByRole('button',{name:'Histórico de cálculos',exact:true}).click();await p.getByRole('button',{name:'Abrir quadro negro',exact:true}).click();await p.locator('.history-board').waitFor();assert.ok(await p.locator('.history-separator time').textContent());await p.screenshot({path:new URL(name+'-blackboard.png',import.meta.url).pathname});await p.getByRole('button',{name:'Voltar à calculadora',exact:true}).press('Enter');await p.locator('.history-board').waitFor({state:'detached'});
 await p.locator('.brand').tap();await drag('.hp-menu-header',80);await p.locator('.hp-menu').waitFor({state:'detached'});
 // Trusted touch drag in Chromium; other browser pointer simulation has no native touch driver.
 if(name==='chromium'){const s=await c.newCDPSession(p);await s.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:201,y:10,id:1}]});await s.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:201,y:85,id:1}]});await s.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await p.locator('.history-board').waitFor();await p.keyboard.press('Escape');await p.locator('.history-board').waitFor({state:'detached'});}
 await p.reload();assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('hp12c-history-v1')).length),2);
 await p.addInitScript(()=>{const h=Array.from({length:100},(_,i)=>({id:'line'+i,time:new Date().toISOString(),operation:'2 + 3',display:'5',value:5}));localStorage.setItem('hp12c-history-v1',JSON.stringify(h))});await p.reload();await p.locator('.brand').tap();await p.getByRole('button',{name:'Histórico de cálculos',exact:true}).click();await p.getByRole('button',{name:'Abrir quadro negro',exact:true}).click();assert.equal(await p.locator('.history-board li').count(),100);assert.equal(await p.locator('.history-board-lines').evaluate(e=>getComputedStyle(e).touchAction),'pan-y');await p.locator('.history-board-lines').evaluate(e=>e.scrollTop=e.scrollHeight);assert.ok(await p.locator('.history-board-lines').evaluate(e=>e.scrollTop)>0);assert.equal(await p.locator('.history-board').count(),1);
 if(name==='chromium'){const s=await c.newCDPSession(p),oldScroll=await p.locator('.history-board-lines').evaluate(e=>e.scrollTop);await s.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:200,y:450,id:1}]});for(let y=475;y<=650;y+=25){await s.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:200,y,id:1}]});await p.waitForTimeout(16)}await s.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await p.waitForTimeout(150);assert.ok(await p.locator('.history-board-lines').evaluate(e=>e.scrollTop)<oldScroll);assert.equal(await p.locator('.history-board').count(),1)}
 await p.setViewportSize({width:874,height:402});await p.waitForTimeout(200);assert.equal(await p.locator('.history-board li').count(),100);await p.getByRole('button',{name:'Voltar à calculadora',exact:true}).click();assert.deepEqual(errors,[]);
 await p.screenshot({path:new URL(name+'-landscape.png',import.meta.url).pathname});results.push({engine:name,passed:true,historyPersistence:true,rows100:true,gestureThreshold56:true,menuDownBoardUp:true,trustedTouch:name==='chromium',errors});await browser.close();
}
await fs.writeFile(new URL('interaction-results.json',import.meta.url),JSON.stringify(results,null,2));console.log(JSON.stringify(results));
