import {createRequire} from 'node:module';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const require=createRequire(import.meta.url);const {chromium}=require('C:/Users/mrpir/AppData/Local/Temp/hp12c-perf-tools/node_modules/playwright');const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'}),page=await browser.newPage({viewport:{width:402,height:874},hasTouch:true,reducedMotion:'reduce'});
await page.addInitScript(()=>{localStorage.setItem('hp12c-history-v1',JSON.stringify(Array.from({length:100},(_,i)=>({id:'long'+i,time:'2026-10-06T12:00:00Z',operation:`Operação ${i} + 2`,display:String(i+2),value:i+2,note:i===99?'Nota final preservada':''}))));window.copied='';Object.defineProperty(navigator,'share',{configurable:true,value:undefined});Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:text=>{window.copied=text;return Promise.resolve()}}})});
await page.goto(process.argv[2]||'http://127.0.0.1:5198');await page.locator('.brand').waitFor();await page.waitForFunction(()=>localStorage.getItem('hp12c-state'));const state=await page.evaluate(()=>localStorage.getItem('hp12c-state')),cdp=await page.context().newCDPSession(page),r=await page.locator('.silver-panel').boundingBox(),x=r.x+r.width/2,y=r.y+20;
await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x,y:y+90,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.locator('.history-board').waitFor();assert.equal(await page.locator('.history-calculation-row').count(),100);
await page.getByRole('button',{name:'Compartilhar bloco de 100 operações'}).tap();await page.getByRole('dialog',{name:'Compartilhar bloco'}).waitFor();await page.waitForFunction(()=>document.querySelectorAll('.history-share-preview').length>1);
const text=await page.getByRole('textbox').inputValue();assert.ok(text.includes('Início não confirmado'));assert.ok(text.includes('Operação 0 + 2')&&text.includes('Operação 99 + 2')&&text.includes('Nota final preservada'));
await page.getByRole('button',{name:'Compartilhar texto',exact:true}).click();await page.getByText('Texto copiado.',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>copied),text);
await page.getByRole('button',{name:'Compartilhar imagem',exact:true}).click();await page.getByText('Baixe cada página pelos botões abaixo ou compartilhe o texto completo.',{exact:true}).waitFor();const pages=await page.locator('.history-share-preview').count();assert.equal(await page.getByRole('button',{name:/Baixar PNG/}).count(),pages);
const dimensions=await page.locator('.history-share-preview').evaluateAll(imgs=>imgs.map(img=>({width:img.naturalWidth,height:img.naturalHeight})));assert.ok(dimensions.every(size=>size.width===1000&&size.height<=3780));await page.screenshot({path:new URL('long-dialog.png',import.meta.url).pathname.replace(/^\/(\w:)/,'$1')});await page.getByRole('button',{name:'Fechar',exact:true}).click();await page.getByRole('button',{name:'Voltar à calculadora'}).click();assert.equal(await page.evaluate(()=>localStorage.getItem('hp12c-state')),state);
await page.locator('.key-clx').click();await page.waitForTimeout(200);const once=await page.evaluate(()=>JSON.parse(localStorage.getItem('hp12c-history-v1')));await page.locator('.key-clx').click();await page.waitForTimeout(200);assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('hp12c-history-v1'))),once);
const result={rows100:true,partial:true,touch:true,reducedMotion:true,pages,dimensions,clipboardComplete:true,noNativeShareFallback:true,repeatedClxNoNewSeparator:true,financialStatePreserved:true};await fs.writeFile(new URL('long-results.json',import.meta.url),JSON.stringify(result,null,2));console.log(JSON.stringify(result));await browser.close();

