import {createRequire} from 'node:module';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const require=createRequire(import.meta.url);const {chromium,webkit}=require('C:/Users/mrpir/AppData/Local/Temp/hp12c-perf-tools/node_modules/playwright');const results=[];
for(const engine of ['chromium','webkit'])for(const viewport of [{width:402,height:874},{width:1280,height:800}]){
 const browser=await (engine==='webkit'?webkit:chromium).launch(engine==='webkit'?{headless:true}:{headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});
 const page=await browser.newPage({viewport,hasTouch:engine==='chromium'}),errors=[];page.on('pageerror',e=>errors.push(String(e)));
 await page.addInitScript(()=>{localStorage.setItem('hp12c-history-v1',JSON.stringify([{id:'a',time:'2026-10-06T12:00:00Z',operation:'2 + 3',display:'5',value:5,note:'Primeira nota'},{id:'b',time:'2026-10-06T12:00:01Z',operation:'5 × 4',display:'20',value:20,note:'Segunda nota'},{id:'c',time:'2026-10-06T12:00:02Z',kind:'separator',operation:'CLX',display:'',value:null},{id:'d',time:'2026-10-06T12:00:03Z',kind:'separator',operation:'CLX',display:'',value:null},{id:'e',time:'2026-10-06T12:00:04Z',operation:'8 ÷ 2',display:'4',value:4}]));window.shareCalls=[];window.shareMode='shared';Object.defineProperty(navigator,'share',{configurable:true,value:data=>{window.shareCalls.push({text:data.text,files:data.files?.length});return window.shareMode==='cancelled'?Promise.reject(new DOMException('Cancel','AbortError')):window.shareMode==='failed'?Promise.reject(new Error('Failure')):Promise.resolve()}});Object.defineProperty(navigator,'canShare',{configurable:true,value:()=>true})});
 await page.goto(process.argv[2]||'http://127.0.0.1:5198');await page.locator('.brand').waitFor();const initial=await page.evaluate(()=>localStorage.getItem('hp12c-history-v1'));
 const r=await page.locator('.silver-panel').boundingBox();await page.mouse.move(r.x+r.width/2,r.y+20);await page.mouse.down();await page.mouse.move(r.x+r.width/2,r.y+110,{steps:6});await page.mouse.up();await page.locator('.history-board').waitFor();await page.waitForTimeout(300);
 assert.equal(await page.locator('.history-board [data-history-action="share"]').count(),2);assert.equal(await page.locator('.history-board .history-calculation-row [data-history-action="share"]').count(),0);
 const share=page.getByRole('button',{name:'Compartilhar bloco de 2 operações',exact:true});await share.focus();await page.keyboard.press('Enter');await page.getByRole('dialog',{name:'Compartilhar bloco'}).waitFor();
 const text=await page.getByRole('textbox',{name:'Texto do bloco para compartilhar'}).inputValue();assert.ok(text.indexOf('2 + 3')<text.indexOf('5 × 4'));assert.ok(text.includes('Primeira nota')&&text.includes('Segunda nota')&&text.includes('Última saída: 20'));
 await page.getByRole('button',{name:'Compartilhar imagem',exact:true}).waitFor();await page.waitForFunction(()=>!Array.from(document.querySelectorAll('button')).find(b=>b.textContent==='Compartilhar imagem')?.disabled);
 await page.getByRole('button',{name:'Compartilhar texto',exact:true}).click();await page.getByText('Compartilhamento concluído.',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>shareCalls.length),1);
 await page.evaluate(()=>shareMode='cancelled');await page.getByRole('button',{name:'Compartilhar imagem',exact:true}).click();await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>shareCalls.at(-1).files),1);assert.equal(await page.getByText('Download da página solicitado.',{exact:true}).count(),0);
 await page.evaluate(()=>shareMode='failed');await page.getByRole('button',{name:'Compartilhar texto',exact:true}).click();await page.getByText('Não foi possível compartilhar. Use copiar ou baixar.',{exact:true}).waitFor();
 await page.getByRole('checkbox').uncheck();assert.ok(!(await page.getByRole('textbox').inputValue()).includes('Primeira nota'));await page.getByRole('checkbox').check();await page.waitForFunction(()=>document.querySelectorAll('.history-share-preview').length===1);
 const downloadEvent=page.waitForEvent('download');await page.getByRole('button',{name:/Baixar PNG/}).click();const download=await downloadEvent;await download.saveAs(new URL(`${engine}-${viewport.width}.png`,import.meta.url).pathname.replace(/^\/(\w:)/,'$1'));
 await page.screenshot({path:new URL(`${engine}-${viewport.width}-dialog.png`,import.meta.url).pathname.replace(/^\/(\w:)/,'$1')});await page.keyboard.press('Escape');await page.getByRole('dialog',{name:'Compartilhar bloco'}).waitFor({state:'detached'});assert.equal(await page.evaluate(()=>localStorage.getItem('hp12c-history-v1')),initial);assert.deepEqual(errors,[]);
 results.push({engine,viewport,groups:2,noEmptyGroups:true,keyboard:true,textChronological:true,notesDefault:true,nativeShareStub:true,cancelNoFallback:true,failureExplicit:true,pngDownload:true,historyPreserved:true,errors});await browser.close();
}
await fs.writeFile(new URL('results.json',import.meta.url),JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2));
