import {useEffect,useRef,useState} from 'react';
import {usePanelMotion} from './usePanelMotion';
import {useSurfacePull} from './useSurfacePull';
import {HpIcon} from './HpIcon';
import './hp-menu.css';
import {CacheStatus} from './CacheStatus';
const options=[['settings','settings','Configurações'],['summary','info','Sobre e dados locais'],['reset','rotate-ccw','Redefinir']];
export function HpMenu({state,prefs,setPrefs,onDisplaySettings,onClose,onReset,onBackup,onRestore,onFullscreen,onDiagnostics,onAngular,onRestoreProgram,onPower}){
 const [route,setRoute]=useState('menu'),[error,setError]=useState(''),[selected,setSelected]=useState({values:false,program:false,settings:false,history:false});
 const heading=useRef(null),panel=useRef(null),lastFocus=useRef(document.activeElement),[bodyAtTop,setBodyAtTop]=useState(true);
 const motion=usePanelMotion(panel,1,onClose);useSurfacePull(panel,motion.close,true,'.hp-menu-body',motion.progress,{freeMotion:true,onStart:motion.begin});
 const capabilities={sound:Boolean(window.AudioContext||window.webkitAudioContext),vibration:typeof navigator.vibrate==='function',fullscreen:typeof document.documentElement.requestFullscreen==='function'};
 const go=r=>{setError('');setRoute(r)};
 useEffect(()=>{heading.current?.focus({preventScroll:true})},[route]);
 useEffect(()=>{const initial=lastFocus.current;return()=>queueMicrotask(()=>initial?.focus?.({preventScroll:true}))},[]);
 const keyDown=e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();route==='menu'?motion.close():go('menu')}if(e.key==='Tab'){const els=[...panel.current.querySelectorAll('button,input,select,[tabindex="0"]')].filter(el=>!el.disabled&&el.getClientRects().length);const first=els[0],last=els.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===heading.current)){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};
 const setting=(label,control,detail)=><div className="hp-setting"><div><span>{label}</span>{detail&&<small>{detail}</small>}</div>{control}</div>;
 const toggle=(key,label)=><button className={`hp-switch ${prefs[key]?'is-on':''}`} role="switch" aria-label={label} aria-checked={prefs[key]} onClick={()=>setPrefs(p=>({...p,[key]:!p[key]}))}><span/></button>;
 const decimals=[...new Set([...Array.from({length:10},(_,i)=>i),state.decimals])].sort((a,b)=>a-b);
 const title=route==='menu'?'HP12C Platinum':options.find(o=>o[0]===route)?.[2]||'Programa de taxas';
 return <div className="menu-shade hp-menu-shade"><section ref={panel} className="menu-panel hp-menu" role="dialog" aria-modal="true" aria-label="Menu da calculadora" onKeyDown={keyDown}><span className="panel-reveal-bar" aria-hidden="true"/>
 <header className="hp-menu-header"><button className="hp-menu-back" aria-label={route==='menu'?'Fechar menu':'Voltar ao menu HP'} onClick={()=>route==='menu'?motion.close():go('menu')}><HpIcon name={route==='menu'?'x':'chevron-left'}/></button><div><h1 ref={heading} tabIndex={-1}>{title}</h1>{route==='menu'&&<p>Calculadora financeira</p>}</div><img src={`${import.meta.env.BASE_URL}assets/hp-emblem-hd.png`} alt="HP"/></header>
 <div className="hp-menu-body" data-pull-at-top={bodyAtTop} onScroll={e=>setBodyAtTop(e.currentTarget.scrollTop<=1)}>{error&&<p className="hp-error" role="alert">{error}</p>}
 {route==='menu'&&<div className="hp-menu-group">{options.map(([id,icon,label])=><button className="hp-menu-row" key={id} onClick={()=>go(id)}><HpIcon name={icon}/><span>{label}</span><HpIcon name="chevron-right"/></button>)}</div>}
 {route==='settings'&&<><div className="hp-menu-group">
 {setting('Casas decimais',<select aria-label="Casas decimais" value={state.decimals} onChange={e=>onDisplaySettings({decimals:Number(e.target.value),fixed:true})}>{decimals.map(n=><option key={n} value={n}>{n}</option>)}</select>,'FIX altera a apresentação; a precisão interna do motor permanece a mesma.')}
 {setting('Formato',<select aria-label="Formato numérico" value={state.fixed?'fixed':'scientific'} onChange={e=>onDisplaySettings({fixed:e.target.value==='fixed'})}><option value="fixed">FIX</option><option value="scientific">Científico</option></select>)}
 {setting('Separador decimal',<select aria-label="Separador decimal" value={state.decimalComma?'comma':'point'} onChange={e=>onDisplaySettings({decimalComma:e.target.value==='comma'})}><option value="comma">Vírgula</option><option value="point">Ponto</option></select>,'Escolhas salvas neste navegador até você mudá-las ou apagar os dados locais.')}
 {setting('Suspender',<select aria-label="Suspender" value={prefs.suspendSeconds} onChange={e=>setPrefs(p=>({...p,suspendSeconds:Number(e.target.value)}))}>{[0,30,60,300].map(n=><option key={n} value={n}>{n?n+' segundos':'Nunca'}</option>)}</select>)}
 {capabilities.sound&&setting('Som',toggle('sound','Som das teclas'))}{capabilities.vibration&&setting('Vibração',toggle('vibration','Vibração das teclas'))}
 {capabilities.fullscreen&&setting('Tela cheia',<button className="hp-inline-action" onClick={onFullscreen}>Alternar</button>)}
 </div><div className="hp-menu-group hp-utility-group"><button className="hp-menu-row" onClick={onAngular}>Ângulos: {state.angular}</button><button className="hp-menu-row" onClick={onPower}>{state.powered?'Desligar':'Ligar'} calculadora</button><button className="hp-menu-row" onClick={onDiagnostics}>Diagnóstico da tela</button><button className="hp-menu-row" onClick={onBackup}>Salvar backup</button><button className="hp-menu-row" onClick={onRestore}>Restaurar backup</button><button className="hp-menu-row" onClick={()=>go('restore-program')}>Restaurar programa de taxas</button></div></>}
 {route==='restore-program'&&<div className="hp-menu-group hp-copy"><h2>Substituir o programa atual?</h2><p>Substitui somente as instruções pelo programa de taxas equivalente. Salve um backup antes.</p><button className="hp-danger" onClick={()=>{onRestoreProgram();go('settings')}}>Substituir programa</button><button onClick={()=>go('settings')}>Cancelar</button></div>}
 {route==='summary'&&<div className="hp-menu-group hp-copy"><p>Motor local independente: RPN/ALG, programas e 20 registradores. Nenhum cálculo é enviado a um servidor.</p><p>Configurações e dados permanecem neste navegador enquanto seus dados locais não forem apagados. A aba e o app instalado podem usar armazenamentos separados; salve backup antes de remover o app.</p><CacheStatus/><a href={`${import.meta.env.BASE_URL}legal/third-party-notices.txt`}>Avisos de terceiros</a></div>}
 {route==='reset'&&<div className="hp-menu-group hp-copy"><h2>Escolha exatamente o que apagar</h2>{[['values','Pilha, registradores e dados financeiros'],['program','Programa atual'],['settings','Configurações'],['history','Histórico e notas']].map(([id,label])=><label className="hp-reset-choice" key={id}><input type="checkbox" checked={selected[id]} onChange={e=>setSelected(s=>({...s,[id]:e.target.checked}))}/>{label}</label>)}<button onClick={onBackup}>Salvar backup antes</button><button className="hp-danger" disabled={!Object.values(selected).some(Boolean)} onClick={()=>go('confirm-reset')}>Continuar</button></div>}
 {route==='confirm-reset'&&<div className="hp-menu-group hp-copy"><h2>Confirmar redefinição?</h2><p>Somente os grupos selecionados serão apagados.</p><button className="hp-danger" onClick={()=>{onReset(selected);onClose()}}>Confirmar redefinição</button><button onClick={()=>go('reset')}>Cancelar</button></div>}
 </div><footer className="hp-menu-version">v{import.meta.env.VITE_APP_VERSION}</footer></section></div>;
}
