import {useEffect,useRef,useState} from 'react';
import {usePanelMotion} from './usePanelMotion';
import {useSurfacePull} from './useSurfacePull';
import {KEY_DEFINITIONS} from '@sagittaryuz/hp12c-core';
import {HpIcon} from './HpIcon';
import {InstallationGuide} from './InstallationGuide';
import './hp-menu.css';
import {CacheStatus} from './CacheStatus';
const options=[['settings','settings','Configurações'],['history','rotate-ccw','Histórico de cálculos'],['memories','database','Memórias'],['shortcuts','keyboard','Atalhos úteis'],['guide','book-open','Guia do usuário'],['summary','info','Resumo do Aplicativo'],['news','sparkles','Quais as Novidades?'],['install','download','Como instalar'],['reset','rotate-ccw','Redefinir']];
export function HpMenu({state,history,prefs,setPrefs,onClose,onRecall,onEditMemory,onReset,onClearHistory,onBoard,onBackup,onRestore,onFullscreen,onDiagnostics,onAngular,onRestoreProgram,onPower}){
 const [route,setRoute]=useState('menu'),[error,setError]=useState(''),[selected,setSelected]=useState({values:false,program:false,settings:false,history:false});
 const [edit,setEdit]=useState(null),[draft,setDraft]=useState('');
 const [locked,setLocked]=useState(false),[isFullscreen,setFullscreen]=useState(Boolean(document.fullscreenElement));
 const heading=useRef(null),panel=useRef(null),lastFocus=useRef(document.activeElement);
 const [bodyAtTop,setBodyAtTop]=useState(true);
 const motion=usePanelMotion(panel,1,onClose);
 useSurfacePull(panel,motion.close,true,'.hp-menu-body',motion.progress);
 const capabilities={sound:Boolean(window.AudioContext||window.webkitAudioContext),vibration:typeof navigator.vibrate==='function',orientation:typeof screen.orientation?.lock==='function',fullscreen:typeof document.documentElement.requestFullscreen==='function'};
 const go=r=>{setError('');setEdit(null);setRoute(r)};
 useEffect(()=>{heading.current?.focus({preventScroll:true})},[route]);
 useEffect(()=>{const initial=lastFocus.current;const fullscreen=()=>setFullscreen(Boolean(document.fullscreenElement));document.addEventListener('fullscreenchange',fullscreen);return()=>{document.removeEventListener('fullscreenchange',fullscreen);queueMicrotask(()=>initial?.focus?.({preventScroll:true}))}},[]);
 const keyDown=e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();route==='menu'?motion.close():go('menu')}if(e.key==='Tab'){const els=[...panel.current.querySelectorAll('button,input,select,[tabindex="0"]')].filter(el=>!el.disabled&&el.getClientRects().length);const first=els[0],last=els.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===heading.current)){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};
 const toggleLandscape=async()=>{try{if(locked){screen.orientation.unlock();setLocked(false)}else{await screen.orientation.lock('landscape');setLocked(true)}}catch{setError('Este navegador não permitiu bloquear a orientação. No iPhone, use o controle de orientação do sistema.')}};
 const toggle=(key,value)=>setPrefs(p=>({...p,[key]:value}));
 const setting=(label,value,control,detail)=> <div className="hp-setting"><div><span>{label}</span>{detail&&<small>{detail}</small>}</div>{control||<span className="hp-setting-value">{value}</span>}</div>;
 const switchControl=(key,label,supported)=> <button className={`hp-switch ${prefs[key]&&supported?'is-on':''}`} role="switch" aria-label={label} aria-checked={Boolean(prefs[key]&&supported)} disabled={!supported} onClick={()=>toggle(key,!prefs[key])}><span/></button>;
 const title=route==='menu'?'HP12C Platinum':options.find(o=>o[0]===route)?.[2]||'HP12c';
 return <div className="menu-shade hp-menu-shade"><section ref={panel} className="menu-panel hp-menu" role="dialog" aria-modal="true" aria-label="Menu da calculadora" onKeyDown={keyDown}><span className="panel-reveal-bar" aria-hidden="true"/>
  <header className={`hp-menu-header ${route==='settings'?'hp-settings-header':''}`}><button className="hp-menu-back" aria-label={route==='menu'?'Fechar menu':'Voltar ao menu HP'} onClick={()=>route==='menu'?motion.close():go('menu')}><HpIcon name={route==='menu'?'x':'chevron-left'}/></button><div><h1 ref={heading} tabIndex={-1}>{title}</h1>{route==='menu'&&<p>Calculadora financeira</p>}</div><img src={`${import.meta.env.BASE_URL}assets/hp-emblem-hd.png`} alt="HP"/></header>
  <div className="hp-menu-body" data-pull-at-top={bodyAtTop} onScroll={e=>setBodyAtTop(e.currentTarget.scrollTop<=1)}>
   {error&&<p className="hp-error" role="alert">{error}</p>}
   {route==='menu'&&<><h2 className="hp-group-title">OPÇÕES</h2><div className="hp-menu-group">{options.map(([id,icon,label])=><button className="hp-menu-row" key={id} onClick={()=>go(id)}><HpIcon name={icon}/><span>{label}</span><HpIcon name="chevron-right" className="hp-chevron"/></button>)}</div></>}
   {route==='settings'&&<><div className="hp-menu-group">
    {setting('HP12C Platinum','Calculadora financeira',null,'Nome do aplicativo.')}
    {setting('Idioma','Português',null,'Interface em português nesta versão.')}
    {setting('Suspender',null,<select aria-label="Suspender" value={prefs.suspendSeconds} onChange={e=>toggle('suspendSeconds',Number(e.target.value))}><option value={0}>Nunca</option><option value={30}>30 segundos</option><option value={60}>1 minuto</option><option value={300}>5 minutos</option></select>,'Desliga só a calculadora por inatividade; não bloqueia o aparelho.')}
    {setting('Som',null,switchControl('sound','Som das teclas',capabilities.sound),capabilities.sound?'Pode depender do volume e das permissões do aparelho.':'Áudio não disponível neste navegador.')}
    {setting('Vibração',null,switchControl('vibration','Vibração das teclas',capabilities.vibration),capabilities.vibration?'Depende do dispositivo.':'Não disponível neste navegador, incluindo Safari no iPhone.')}
    {setting('Entrada de tecla',null,<select aria-label="Entrada de tecla" value="release" disabled><option value="press">Ao pressionar</option><option value="release">Ao soltar</option></select>,'Os toques são confirmados ao soltar para permitir o arraste de histórico sem executar teclas. Atalhos de teclado permanecem imediatos.')}
    {setting('Bloqueio paisagem',null,<button className={`hp-switch ${locked?'is-on':''}`} role="switch" aria-label="Bloqueio paisagem" aria-checked={locked} disabled={!capabilities.orientation} onClick={toggleLandscape}><span/></button>,capabilities.orientation?'Pode exigir tela cheia. Só indica ativo após confirmação da API.':'O navegador não oferece bloqueio de orientação; use o sistema.')}
    {setting('Layout retrato','Moderno',null,'O layout atual é preservado; não há um layout alternativo nesta versão.')}
    {setting('Separador decimal','Vírgula',null,'Mantido conforme o padrão definido para esta calculadora.')}
    {setting('Tela cheia',null,<button className="hp-inline-action" disabled={!capabilities.fullscreen} onClick={onFullscreen}>{isFullscreen?'Sair':'Abrir'}</button>,capabilities.fullscreen?'Usa a tela cheia liberada pelo navegador.':'No iPhone, abra o ícone adicionado à Tela de Início.')}
   </div><div className="hp-menu-group hp-utility-group"><button className="hp-menu-row" onClick={onAngular}><span>Ângulos: {state.angular}</span><HpIcon name="chevron-right"/></button><button className="hp-menu-row" onClick={onPower}><span>{state.powered?'Desligar':'Ligar'} calculadora</span></button><button className="hp-menu-row" onClick={onDiagnostics}><span>Diagnóstico da tela</span><HpIcon name="chevron-right"/></button><button className="hp-menu-row" onClick={onBackup}><span>Salvar backup</span></button><button className="hp-menu-row" onClick={onRestore}><span>Restaurar backup</span></button></div></>}
   {route==='history'&&<><button className="hp-secondary" onClick={onBoard}>Abrir quadro negro</button><p className="hp-help">Reutilizar traz o valor para X com as regras de recall do motor. No RPN, a pilha sobe quando o lift está ativo.</p>{!history.length&&<p className="hp-help">Nenhum cálculo registrado nesta revisão.</p>}<div className="hp-menu-group">{[...history].reverse().map(item=><div className="hp-history-item" key={item.id}><span>{item.operation}</span><strong>{item.display}</strong><small>{new Date(item.time).toLocaleString('pt-BR')}</small><button disabled={!Number.isFinite(item.value)} onClick={()=>{try{onRecall(item.value);onClose()}catch(e){setError(e.message)}}}>Reutilizar resultado</button></div>)}</div>{history.length>0&&<button className="hp-secondary" onClick={()=>go('clear-history')}>Limpar histórico…</button>}</>}
   {route==='clear-history'&&<div className="hp-menu-group hp-copy"><h2>Apagar somente o histórico?</h2><p>A pilha, os programas, as memórias e as configurações serão mantidos.</p><button className="hp-danger" onClick={()=>{onClearHistory();go('history')}}>Apagar histórico</button><button className="hp-secondary" onClick={()=>go('history')}>Cancelar</button></div>}
   {route==='memories'&&<><p className="hp-help">R0–R9 e R.0–R.9. Editar não muda X nem a pilha. Registradores com fluxo de caixa existente são sincronizados como no STO.</p><div className="hp-menu-group">{state.registers.map((value,i)=><div className="hp-memory-row" key={i}><strong>{i<10?'R'+i:'R.'+(i-10)}</strong><span>{String(value).replace('.',',')}</span><button aria-label={`Editar ${i<10?'R'+i:'R.'+(i-10)}`} onClick={()=>{setEdit(i);setDraft(String(value).replace('.',','))}}>Editar</button></div>)}</div>{edit!==null&&<form className="hp-memory-editor" onSubmit={e=>{e.preventDefault();try{onEditMemory(edit,draft);setEdit(null);setError('')}catch(error){setError(error.message)}}}><label>Valor de {edit<10?'R'+edit:'R.'+(edit-10)}<input autoFocus inputMode="decimal" value={draft} onChange={e=>setDraft(e.target.value)}/></label><button type="submit">Salvar registrador</button><button type="button" onClick={()=>setEdit(null)}>Cancelar</button></form>}</>}
   {route==='shortcuts'&&<div className="hp-menu-group hp-copy"><h2>Teclado físico</h2><dl className="hp-shortcut-list">{KEY_DEFINITIONS.filter(k=>!['on','swap'].includes(k.id)).map(k=><div key={k.id}><dt>{k.label}</dt><dd>{k.shortcut}</dd></div>)}</dl><p>Vírgula equivale ao ponto decimal; Espaço equivale a ENTER. Backspace apaga a entrada. Atalhos da calculadora ficam pausados enquanto o menu está aberto.</p></div>}
   {route==='guide'&&<div className="hp-menu-group hp-copy"><h2>Guia rápido</h2><p>RPN: digite 2, ENTER, 3 e + para obter 5. ENTER separa os operandos.</p><p>f + 0–9 escolhe FIX. f + ponto ativa notação científica. A entrada preserva os dígitos informados; o padrão inicial é sete casas.</p><p>STO + número salva X; RCL + número recupera o registrador. Use ponto antes do número para R.0–R.9.</p><p>Taxas equivalentes: taxa em i, período de origem em n, período de destino em X; R/S executa o programa inicial, se ele ainda estiver carregado.</p><button className="hp-secondary" onClick={()=>go('restore-program')}>Restaurar programa de taxas…</button><p>O motor é independente. Não é uma reprodução certificada do firmware HP do fabricante.</p></div>}
   {route==='restore-program'&&<div className="hp-menu-group hp-copy"><h2>Substituir o programa atual?</h2><p>Essa ação substitui as instruções do programa pelo programa de taxas equivalente. Registradores e formato FIX são preservados. Salve backup antes.</p><button className="hp-danger" onClick={()=>{onRestoreProgram();go('guide')}}>Substituir programa</button><button className="hp-secondary" onClick={()=>go('guide')}>Cancelar</button></div>}
   {route==='summary'&&<div className="hp-menu-group hp-copy"><h2>HP 12c Platinum</h2><p>Calculadora financeira independente com motor local, modos RPN/ALG, programas e registradores persistidos neste navegador.</p><p>Nenhum cálculo é enviado a um servidor. Os dados do app instalado podem ser separados dos dados da aba Safari. Use Salvar backup antes de remover o app ou limpar dados.</p><p>Tela cheia e orientação dependem do navegador e do sistema operacional. O app não controla os pixels reservados à barra de status.</p></div>}
   {route==='news'&&<div className="hp-menu-group hp-copy"><h2>Atualização 0.2.11</h2><p>Faixa superior fixa e opaca para a amostragem de cor do Safari. O efeito sobre o desfoque da barra do iOS precisa ser confirmado no aparelho.</p><p>Cabeçalho e visor elevados em mais até 10 px, respeitando áreas seguras. Teclado, placas, base e dados salvos preservados.</p></div>}
   {route==='reset'&&<div className="hp-menu-group hp-copy"><h2>Escolha exatamente o que apagar</h2><p>Nenhuma ação ocorre ao abrir esta tela. As opções não selecionadas serão preservadas.</p>{[['values','Pilha, registradores, dados financeiros e fluxos de caixa'],['program','Programa atual e posição de execução'],['settings','Configurações do motor e preferências de interface'],['history','Histórico de cálculos']].map(([id,label])=><label className="hp-reset-choice" key={id}><input type="checkbox" checked={selected[id]} onChange={e=>setSelected(s=>({...s,[id]:e.target.checked}))}/>{label}</label>)}<button className="hp-secondary" onClick={onBackup}>Salvar backup antes</button><button className="hp-danger" disabled={!Object.values(selected).some(Boolean)} onClick={()=>go('confirm-reset')}>Revisar exclusão…</button></div>}
   {route==='confirm-reset'&&<div className="hp-menu-group hp-copy"><h2>Confirmar exclusão selecionada?</h2><ul>{Object.entries(selected).filter(([,v])=>v).map(([k])=><li key={k}>{({values:'Pilha e dados financeiros',program:'Programa',settings:'Configurações',history:'Histórico'})[k]}</li>)}</ul><p>Essa ação só apaga os itens listados acima.</p><button className="hp-danger" onClick={()=>{onReset(selected);onClose()}}>Apagar somente estes itens</button><button className="hp-secondary" onClick={()=>go('reset')}>Cancelar</button></div>}
  </div>
  <CacheStatus/><footer className="hp-menu-version">HP12C Platinum · v{import.meta.env.VITE_APP_VERSION}<small>Marcos Rodrigues Pires, 2026</small><small>Build {import.meta.env.VITE_BUILD_TIME}</small></footer>
  {route==='install'&&<InstallationGuide onClose={()=>go('menu')}/>}
 </section></div>;
}
