import {useLayoutEffect,useRef} from 'react';
import {animatePanel} from './panel-motion.mjs';
export function usePanelMotion(surface,direction,onClosed,start=0){
 const state=useRef({alive:true,closing:false,y:0,entry:[],movement:null}),latest=useRef(onClosed);latest.current=onClosed;
 const cancelEntry=()=>{for(const a of state.current.entry)a.cancel();state.current.entry=[]};
 const cancelMovement=()=>{state.current.movement?.cancel();state.current.movement=null};
 const progress=distance=>{const s=state.current,el=surface.current;if(!el||s.closing)return;cancelMovement();const previous=s.y,y=direction*Math.max(0,distance);s.y=y;el.style.transform=`translate3d(0,${y}px,0)`;if(!distance&&previous){const a=animatePanel(el,[{transform:`translate3d(0,${previous}px,0)`},{transform:'translate3d(0,0,0)'}],160);s.movement=a;a.finished.then(()=>{if(s.alive&&!s.closing)a.cancel()}).catch(()=>{})}};
 const close=()=>{const s=state.current,el=surface.current;if(!el||s.closing)return;s.closing=true;el.dataset.closing='true';const from=getComputedStyle(el).transform;el.style.clipPath=getComputedStyle(el).clipPath;cancelEntry();cancelMovement();const a=animatePanel(el,[{transform:from==='none'?`translate3d(0,${s.y}px,0)`:from},{transform:`translate3d(0,${direction*el.getBoundingClientRect().height}px,0)`}]);s.movement=a;a.finished.then(()=>{if(s.alive)latest.current()}).catch(()=>{})};
 useLayoutEffect(()=>{const s=state.current,el=surface.current;s.alive=true;if(el.tagName==='DIALOG'&&!el.open)el.showModal();const h=el.getBoundingClientRect().height,bar=el.querySelector('.panel-reveal-bar'),from=Math.min(Math.max(0,start),h);const a=animatePanel(el,[{clipPath:`inset(0 0 ${h-from}px 0)`},{clipPath:'inset(0 0 0px 0)'}]);s.entry=[a];if(bar){bar.hidden=false;s.entry.push(animatePanel(bar,[{transform:`translate3d(0,${Math.max(0,from-3)}px,0)`},{transform:`translate3d(0,${h-3}px,0)`}]))}a.finished.then(()=>{if(s.alive&&!s.closing){cancelEntry();el.style.clipPath='';if(bar)bar.hidden=true}}).catch(()=>{});let lastWidth=el.clientWidth,lastHeight=el.clientHeight;const resize=()=>{if(el.clientWidth===lastWidth&&el.clientHeight===lastHeight)return;lastWidth=el.clientWidth;lastHeight=el.clientHeight;cancelEntry();cancelMovement();if(s.closing)latest.current();else{s.y=0;el.style.transform='';el.style.clipPath='';if(bar)bar.hidden=true}};const media=window.matchMedia('(prefers-reduced-motion: reduce)'),preference=()=>{if(media.matches){cancelEntry();cancelMovement();if(s.closing)latest.current();else{s.y=0;el.style.transform='';el.style.clipPath='';if(bar)bar.hidden=true}}};media.addEventListener('change',preference);window.addEventListener('resize',resize);return()=>{s.alive=false;cancelEntry();cancelMovement();window.removeEventListener('resize',resize);media.removeEventListener('change',preference)}},[surface]);
 return {close,progress};
}
