import {createRequire} from 'node:module';import fs from 'node:fs/promises';import assert from 'node:assert/strict';const require=createRequire(import.meta.url),{chromium,webkit}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/mrpir/AppData/Local/Temp/hp12c-perf-tools/node_modules/playwright');
const results=[],base=process.argv[2]||'http://127.0.0.1:5199';
const fixture=JSON.parse(await fs.readFile(new URL('fixture.json',import.meta.url),'utf8'));
for(const name of ['chromium','webkit'])for(const viewport of [{width:402,height:874},{width:1280,height:800}]){
 const browser=await(name==='webkit'?webkit:chromium).launch(name==='webkit'?{headless:true}:{headless:true,executablePath:process.env.BROWSER_PATH||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'}),context=await browser.newContext({viewport,hasTouch:name==='chromium'}),page=await context.newPage(),errors=[],requests=[];page.on('pageerror',e=>errors.push(String(e)));page.on('request',r=>requests.push(r.url()));
 await context.addInitScript(fixture=>{if(!localStorage.getItem('qa-preserve')){localStorage.setItem('hp12c-state',JSON.stringify(fixture));localStorage.setItem('hp12c-default-program','equivalent-rate-v1');localStorage.setItem('hp12c-default-display','editable-fix-7-v2');localStorage.setItem('hp12c-history-activity-v1','true');localStorage.setItem('hp12c-history-v1',JSON.stringify(Array.from({length:100},(_,i)=>i%10===9?{id:'s'+i,time:'2026-10-06T12:00:00Z',operation:'CLX',display:'',value:null,kind:'separator'}:{id:'h'+i,time:'2026-10-06T12:00:00Z',operation:'2.5 + 100',display:'102,500',value:102.5,...(i===98?{note:'Nota preservada 2.5'}:{})})));}window.copied=[];window.copyFails=false;Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:text=>copyFails?Promise.reject(new Error('blocked')):(copied.push(text),Promise.resolve())}})},fixture);
 await page.goto(base);await page.waitForFunction(()=>document.querySelector('.calculator')?.classList.contains('joined-frame'));await page.evaluate(()=>document.fonts.ready);await page.waitForTimeout(250);
 const saved=()=>page.evaluate(()=>({state:localStorage.getItem('hp12c-state'),history:localStorage.getItem('hp12c-history-v1')}));const initial=await saved(),display=()=>page.locator('output.lcd-readable').innerText();assert.equal(await display(),'2,500');
 const center=async key=>{const r=await page.locator('.key-'+key).boundingBox();return{x:r.x+r.width/2,y:r.y+r.height/2,r}};
 const down=async key=>{const p=await center(key);await page.mouse.move(p.x,p.y);await page.mouse.down();return p};
 await down('plus');assert.equal(await display(),'102,500');await page.waitForTimeout(350);assert.deepEqual(await saved(),initial);await page.mouse.up();await page.waitForTimeout(200);let state=JSON.parse((await saved()).state);assert.equal(state.x,102.5);let history=JSON.parse((await saved()).history);assert.equal(history.length,100);assert.equal(history.filter(item=>!/^h|^s/.test(item.id)).length,1);
 for(const kind of ['move','outside','cancel','blur','keyboard']){
  await page.reload();await page.locator('.key-plus').waitFor();await page.waitForTimeout(220);const before=await saved();const p=await down('plus');assert.equal(await display(),'102,500');
  if(kind==='move')await page.mouse.move(p.x+12,p.y);else if(kind==='outside')await page.mouse.move(p.r.x+p.r.width+3,p.y);else if(kind==='cancel')await page.locator('.key-plus').dispatchEvent('pointercancel',{pointerId:1,bubbles:true});else if(kind==='blur')await page.evaluate(()=>window.dispatchEvent(new Event('blur')));else await page.keyboard.press('1');
  await page.mouse.up();await page.waitForTimeout(200);if(kind==='keyboard'){assert.equal(JSON.parse((await saved()).state).x,1);assert.equal((await saved()).history,before.history)}else assert.deepEqual(await saved(),before);
 }
 await page.reload();await page.locator('.key-sto').waitFor();await page.waitForTimeout(220);await page.locator('.key-sto').click();await page.waitForTimeout(200);const beforeSto=await saved(),stoPoint=await down('0');await page.mouse.move(stoPoint.x+12,stoPoint.y);await page.mouse.up();await page.waitForTimeout(200);assert.deepEqual(await saved(),beforeSto);await page.locator('.key-0').click();await page.waitForTimeout(200);const afterSto=JSON.parse((await saved()).state);assert.equal(afterSto.registers[0],2.5);assert.equal(afterSto.cashflows[0],2.5);assert.equal((await saved()).history,beforeSto.history);
 await page.reload();await page.locator('.key-plus').waitFor();await page.waitForTimeout(220);const edgeBefore=await saved(),edgeRect=(await center('plus')).r;await page.mouse.move(edgeRect.x+edgeRect.width-1,edgeRect.y+edgeRect.height/2);await page.mouse.down();await page.mouse.move(edgeRect.x+edgeRect.width+2,edgeRect.y+edgeRect.height/2);await page.mouse.up();await page.waitForTimeout(200);assert.deepEqual(await saved(),edgeBefore);
 if(name==='chromium'){
  await page.reload();await page.locator('.key-plus').waitFor();await page.waitForTimeout(220);const before=await saved(),p=await center('plus'),p2=await center('1'),cdp=await context.newCDPSession(page);
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:p.x,y:p.y,id:1}]});assert.equal(await display(),'102,500');await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:p.x,y:p.y,id:1},{x:p2.x,y:p2.y,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForTimeout(200);assert.deepEqual(await saved(),before);
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:p.x,y:p.y,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});await page.waitForTimeout(200);assert.deepEqual(await saved(),before);
  await page.reload();await page.locator('.key-1').waitFor();await page.waitForTimeout(220);
  for(const digit of '123456789'){const q=await center(digit);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:q.x,y:q.y,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:q.x+9,y:q.y,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]})}
  await page.waitForTimeout(200);assert.equal(await display(),'123456789','quick mobile taps with small within-key finger drift must all register');
 }
 await page.reload();await page.locator('.key-7').waitFor();await page.waitForTimeout(220);const beforeDrag=await saved(),p=await down('7');assert.equal(await display(),'7');await page.mouse.move(p.x,p.y+90,{steps:6});await page.mouse.up();await page.locator('.history-board').waitFor();await page.waitForTimeout(300);assert.deepEqual(await saved(),beforeDrag);
 assert.equal(await page.locator('.memory-register-grid button').count(),20);const background=await page.locator('.history-board').evaluate(el=>({image:getComputedStyle(el).backgroundImage,color:getComputedStyle(el).backgroundColor,filter:getComputedStyle(el).filter}));assert.deepEqual(background,{image:'none',color:'rgb(9, 9, 9)',filter:'none'});assert.equal(await page.locator('meta[name="theme-color"]').getAttribute('content'),'#090909');
 await page.getByRole('button',{name:/^Editar R\.9:/}).click();await page.getByRole('textbox',{name:'Valor de R.9',exact:true}).fill('123,4567891');await page.getByRole('button',{name:'Salvar registrador',exact:true}).click();await page.waitForTimeout(200);state=JSON.parse((await saved()).state);assert.equal(state.registers[19],123.4567891);assert.equal(state.cashflows[19],state.registers[19]);assert.deepEqual([state.x,state.y,state.z,state.t],[2.5,100,7,8]);assert.deepEqual(state.program,fixture.program);assert.equal((await saved()).history,beforeDrag.history);
 await page.getByRole('button',{name:/^Editar R0:/}).click();await page.getByRole('textbox',{name:'Valor de R0',exact:true}).fill('1e101');await page.getByRole('button',{name:'Salvar registrador',exact:true}).click();await page.getByRole('alert').waitFor();await page.getByRole('button',{name:'Cancelar',exact:true}).click();assert.equal(JSON.parse((await saved()).state).registers[0],.125);
 const copy=page.getByRole('button',{name:'Copiar bloco de 9 operações',exact:true}).first();await copy.scrollIntoViewIfNeeded();await copy.click();await page.getByText('Copiado',{exact:true}).waitFor();assert.equal(await page.locator('.history-dialog').count(),0);const text=await page.evaluate(()=>copied.at(-1));assert.ok(text.includes('Nota preservada 2.5'));assert.ok(text.includes('2,5 + 100'));assert.ok(text.includes('Última saída: 102,500'));
 await page.evaluate(()=>copyFails=true);await copy.click();await page.getByText('Não foi possível copiar.',{exact:true}).waitFor();assert.equal(await page.getByText('Copiado',{exact:true}).count(),0);await page.evaluate(()=>copyFails=false);
 await page.screenshot({path:new URL(`${name}-${viewport.width}-memory.png`,import.meta.url).pathname.replace(/^\/(\w:)/,'$1')});await page.getByRole('button',{name:'Voltar à calculadora'}).click();await page.locator('.history-board').waitFor({state:'detached'});assert.equal(await page.locator('meta[name="theme-color"]').getAttribute('content'),'#c6c6c6');
 await page.locator('.brand').click();assert.equal(await page.getByRole('button',{name:'Histórico de cálculos',exact:true}).count(),0);assert.equal(await page.getByRole('button',{name:'Como instalar',exact:true}).count(),0);await page.getByRole('button',{name:'Configurações',exact:true}).click();await page.getByLabel('Casas decimais',{exact:true}).selectOption('4');await page.getByLabel('Separador decimal',{exact:true}).selectOption('point');await page.waitForTimeout(200);await page.keyboard.press('Escape');await page.keyboard.press('Escape');await page.locator('.hp-menu').waitFor({state:'detached'});assert.equal(await display(),'2.5000');await page.evaluate(()=>localStorage.setItem('qa-preserve','true'));await page.reload();await page.locator('.key-1').waitFor();assert.equal(await display(),'2.5000');await page.evaluate(()=>document.activeElement?.blur());await page.keyboard.press('1');await page.keyboard.press('Enter');assert.equal(await display(),'1.0000');await page.waitForTimeout(200);
 const r=await page.locator('.silver-panel').boundingBox();await page.mouse.move(r.x+r.width/2,r.y+20);await page.mouse.down();await page.mouse.move(r.x+r.width/2,r.y+110,{steps:6});await page.mouse.up();await page.locator('.history-board').waitFor();const copyDot=page.getByRole('button',{name:'Copiar bloco de 9 operações',exact:true}).first();await copyDot.scrollIntoViewIfNeeded();await copyDot.click();await page.getByText('Copiado',{exact:true}).waitFor();assert.ok((await page.evaluate(()=>copied.at(-1))).includes('102.500'));assert.equal(requests.filter(url=>url.includes('memory-board-photo')).length,0);assert.deepEqual(errors,[]);
 results.push({name,viewport,version:'0.2.41',previewBeforeRelease:true,commitOnce:true,storeCancelPreserved:true,smallEdgeExitCancelled:true,cancelMoveOutsideBlur:true,keyboardInvalidatesPreview:true,multitouch:name==='chromium',mobileTouchDriftAccepted:name==='chromium',keyPullStatePreserved:true,rows100:true,registers20:true,precisionAndCashflows:true,copyEntireBlockWithNotes:true,copyFailureNoFalseSuccess:true,solidBackground:background,formatPersisted:true,noPhotoRequests:true,errors});await browser.close();await fs.writeFile(new URL(process.env.QA_OUTPUT||'functional.json',import.meta.url),JSON.stringify(results,null,2));console.log(name+' '+viewport.width+' passed');
}
console.log(JSON.stringify(results,null,2));
