import {createRequire} from 'node:module';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';
const require=createRequire(import.meta.url),{chromium,webkit}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/mrpir/AppData/Local/Temp/hp12c-perf-tools/node_modules/playwright');
const base=process.argv[2]||'http://127.0.0.1:4174',results=[],shots=process.env.QA_SCREENSHOT_DIR||'C:/Users/mrpir/AppData/Local/Temp/hp12c-review';
for(const engine of ['chromium','webkit']){
 const browser=await(engine==='webkit'?webkit:chromium).launch(engine==='webkit'?{headless:true}:{headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});
 for(const viewport of [{width:320,height:450},{width:402,height:874},{width:844,height:390},{width:1280,height:800},{width:1920,height:1080}]){
  const page=await browser.newPage({viewport,hasTouch:engine==='chromium'}),errors=[];page.on('pageerror',e=>errors.push(String(e)));
  await page.addInitScript(()=>{window.shares=[];window.copies=[];window.writes=[];window.responseTimes=[];const set=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){writes.push({key,time:performance.now()});return set.call(this,key,value)};Object.defineProperty(navigator,'share',{configurable:true,value:d=>(shares.push(d),Promise.resolve())});Object.defineProperty(navigator,'canShare',{configurable:true,value:()=>true});Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:text=>(copies.push(text),Promise.resolve())}});let down=0;window.addEventListener('pointerdown',()=>{down=performance.now()},true);new MutationObserver(()=>{if(down){responseTimes.push(performance.now()-down);down=0}}).observe(document,{subtree:true,attributes:true,attributeFilter:['data-display']})});
  await page.goto(base);assert.match(await page.title(),/HP/i);await page.evaluate(()=>document.fonts.ready);await page.waitForTimeout(900);await page.evaluate(()=>writes=[]);
  const output=()=>page.locator('output.lcd-readable').innerText();
  for(const digit of '1234567')await page.locator('.key-'+digit).click();await page.locator('.key-decimal').click();await page.locator('.key-5').click();await page.locator('.key-0').click();assert.equal(await output(),'1.234.567,50');
  await page.evaluate(()=>window.dispatchEvent(new Event('pagehide')));const persisted=await page.evaluate(()=>JSON.parse(localStorage.getItem('hp12c-state')));assert.equal(persisted.input,'1234567.50');assert.equal(persisted.x,1234567.5);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('hp12c-history-v1')).length),0);
  await page.locator('.lcd').click();await page.waitForFunction(()=>copies.length===1);assert.equal(await page.evaluate(()=>shares.length),0);assert.equal(await page.evaluate(()=>copies[0]),'1.234.567,50');
  await page.locator('.key-enter').click();await page.locator('.key-2').click();await page.locator('.key-plus').click();await page.locator('.key-clx').click();await page.locator('.key-7').click();await page.locator('.key-enter').click();await page.evaluate(()=>window.dispatchEvent(new Event('pagehide')));const rows=await page.evaluate(()=>JSON.parse(localStorage.getItem('hp12c-history-v1')));assert.equal(rows.length,1);assert.equal(rows[0].value,1234569.5);
  await page.locator('.brand').click();await page.locator('.history-board').waitFor();assert.equal(await page.locator('.history-calculation-row').count(),1);await page.getByRole('button',{name:'Fechar memória'}).click();await page.locator('.history-board').waitFor({state:'detached'});
  const geometry=await page.evaluate(()=>{const rect=s=>{const r=document.querySelector(s).getBoundingClientRect();return{left:r.left,right:r.right,top:r.top,bottom:r.bottom,width:r.width,height:r.height,center:r.top+r.height/2}},lcd=rect('.lcd'),model=rect('.model-name'),brand=rect('.brand'),left=rect('.key-sin'),right=rect('.key-plus'),frame=rect('.portrait-footer-frame'),last=rect('.key-f');return{lcd,model,brand,left,right,frame,last,modelFont:parseFloat(getComputedStyle(document.querySelector('.model-name')).fontSize),keys:[...document.querySelectorAll('.key')].filter(e=>getComputedStyle(e).display!=='none').map(e=>{const r=e.getBoundingClientRect();return{id:e.className,left:r.left,right:r.right,top:r.top,bottom:r.bottom,height:r.height}})}});
  if(viewport.width>viewport.height){assert.ok(Math.abs(geometry.model.left-geometry.left.left)<1);assert.ok(Math.abs(geometry.brand.right-geometry.right.right)<1);assert.ok(Math.abs(geometry.model.center-geometry.lcd.center)<1);assert.ok(Math.abs(geometry.model.height-geometry.lcd.height)<1);assert.ok(Math.abs((geometry.lcd.left+geometry.lcd.right)/2-viewport.width/2)<1);assert.ok(Math.abs(geometry.brand.center-geometry.lcd.center)<1);assert.ok(geometry.model.right<geometry.lcd.left);assert.ok(geometry.brand.left>geometry.lcd.right);}
  else{assert.equal(viewport.height-geometry.frame.bottom,2);assert.ok(geometry.last.bottom<geometry.frame.bottom-10)}
  for(const key of geometry.keys){assert.ok(key.height>10);assert.ok(key.left>=0&&key.right<=viewport.width+1&&key.top>=0&&key.bottom<=viewport.height)}
  await page.locator('.key-clx').click();if(engine==='chromium'){const cdp=await page.context().newCDPSession(page);await page.evaluate(()=>{writes=[];responseTimes=[]});for(const digit of '1234567890'){const r=await page.locator('.key-'+digit).boundingBox(),x=r.x+r.width/2,y=r.y+r.height/2;await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+5,y,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]})}assert.equal(await output(),'1.234.567.890');assert.equal(await page.evaluate(()=>writes.length),0)}
  const metrics=await page.evaluate(()=>({responses:responseTimes,drawMs:document.querySelector('.lcd-face').dataset.drawMs}));await page.waitForFunction(expected=>JSON.parse(localStorage.getItem('hp12c-state')).input===expected,engine==='chromium'?'1234567890':'0');const before=await page.evaluate(()=>localStorage.getItem('hp12c-state'));await page.setViewportSize(viewport.width<viewport.height?{width:844,height:390}:{width:402,height:874});await page.waitForTimeout(400);await page.setViewportSize(viewport);await page.waitForTimeout(400);assert.equal(await page.evaluate(()=>localStorage.getItem('hp12c-state')),before);
  await page.screenshot({path:path.join(shots,`${engine}-${viewport.width}-final.png`)});assert.deepEqual(errors,[]);results.push({engine,viewport,copyOnly:true,thousandsDuringInput:true,onlyMathHistory:true,geometry,metrics,errors});console.log(engine+' '+viewport.width+' passed');await page.close();
 }
 await browser.close();
}
await fs.writeFile(process.env.QA_OUTPUT||path.join(shots,'input-layout-results.json'),JSON.stringify(results,null,2));
