import {createRequire} from 'node:module';import fs from 'node:fs/promises';import assert from 'node:assert/strict';const require=createRequire(import.meta.url),{chromium,webkit}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/mrpir/AppData/Local/Temp/hp12c-perf-tools/node_modules/playwright'),results=[];
const stats=values=>{values.sort((a,b)=>a-b);return{n:values.length,median:values[Math.floor(values.length/2)],p95:values[Math.floor(values.length*.95)],max:values.at(-1)}};
for(const name of ['chromium','webkit']){
 const browser=await(name==='webkit'?webkit:chromium).launch(name==='webkit'?{headless:true}:{headless:true,executablePath:process.env.BROWSER_PATH||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});const samples=[];
 for(let trial=0;trial<8;trial++)for(const rows of [0,100])for(const version of trial%2?['0.2.39','0.2.38']:['0.2.38','0.2.39']){
  const context=await browser.newContext({viewport:{width:402,height:874},serviceWorkers:'block'});await context.addInitScript(rows=>{
   localStorage.setItem('hp12c-history-v1',JSON.stringify(Array.from({length:rows},(_,i)=>({id:'perf'+i,time:'2026-10-06T12:00:00Z',operation:'2 + 3',display:'5',value:5}))));window.perf={firstCommit:null,rectReads:0,rectMs:0,keyEvents:[],writes:[],canvas:0};let pending=null;
   const rect=Element.prototype.getBoundingClientRect;Element.prototype.getBoundingClientRect=function(){const t=performance.now();const r=rect.call(this);perf.rectReads++;perf.rectMs+=performance.now()-t;return r};
   const clear=CanvasRenderingContext2D.prototype.clearRect;CanvasRenderingContext2D.prototype.clearRect=function(...args){perf.canvas++;return clear.apply(this,args)};
   const setItem=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){perf.writes.push({key,t:performance.now()});return setItem.call(this,key,value)};
   for(const type of ['pointerdown','keydown'])document.addEventListener(type,e=>{if(type==='pointerdown'&&!e.target.closest?.('.key'))return;pending={type,t:performance.now(),before:document.querySelector('output.lcd-readable')?.textContent};perf.keyEvents.push(pending)},true);
   window.__REACT_DEVTOOLS_GLOBAL_HOOK__={supportsFiber:true,inject:()=>1,onCommitFiberRoot(){perf.firstCommit??=performance.now();const display=document.querySelector('output.lcd-readable')?.textContent;if(pending&&pending.response===undefined&&display!==pending.before){pending.response=performance.now()-pending.t;pending.display=display}},onCommitFiberUnmount(){}};
  },rows);const page=await context.newPage();await page.goto(version==='0.2.38'?'http://127.0.0.1:5200':'http://127.0.0.1:5199');await page.waitForFunction(()=>document.querySelector('.calculator')?.classList.contains('joined-frame'));await page.evaluate(()=>document.fonts.ready);await page.waitForTimeout(220);
  const startup=await page.evaluate(()=>({firstCommit:perf.firstCommit,rectReads:perf.rectReads,rectMs:perf.rectMs,domReady:performance.getEntriesByType('navigation')[0].domContentLoadedEventEnd,resources:performance.getEntriesByType('resource').map(r=>({name:r.name,bytes:r.decodedBodySize}))}));
  await page.evaluate(()=>{perf.keyEvents=[];perf.canvas=0;perf.rectReads=0;perf.rectMs=0;perf.writes=[]});const r=await page.locator('.key-1').boundingBox();await page.mouse.move(r.x+r.width/2,r.y+r.height/2);await page.mouse.down();await page.waitForTimeout(150);const beforeRelease=await page.locator('output.lcd-readable').innerText();await page.mouse.up();await page.waitForTimeout(220);const pointer=await page.evaluate(()=>({events:perf.keyEvents,canvas:perf.canvas,rectReads:perf.rectReads,writes:perf.writes}));assert.equal(beforeRelease,version==='0.2.39'?'1':(version==='0.2.38'?'0,0000000':'0,00'));
  await page.keyboard.press('Delete');await page.waitForTimeout(200);await page.evaluate(()=>{document.activeElement?.blur();perf.keyEvents=[];perf.canvas=0;perf.rectReads=0;perf.writes=[]});for(const key of ['1','2','3','4','5','6','7','8','Enter','1','+'])await page.keyboard.press(key);await page.waitForTimeout(220);const rapid=await page.evaluate(()=>({events:perf.keyEvents,canvas:perf.canvas,rectReads:perf.rectReads,writes:perf.writes,display:document.querySelector('output.lcd-readable')?.textContent}));assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('hp12c-state')).x),12345679);
  samples.push({version,rows,trial,startup,pointer,rapid});await context.close();
 }
 const summary=[];for(const version of ['0.2.38','0.2.39'])for(const rows of [0,100]){const selected=samples.filter(s=>s.version===version&&s.rows===rows);summary.push({version,rows,startupCommit:stats(selected.map(s=>s.startup.firstCommit)),startupRectMs:stats(selected.map(s=>s.startup.rectMs)),pointerResponse:stats(selected.map(s=>s.pointer.events[0].response)),rapidKeyResponse:stats(selected.flatMap(s=>s.rapid.events.filter(e=>e.response!==undefined).map(e=>e.response))),rapidRectReads:selected.map(s=>s.rapid.rectReads),stateWrites:selected.map(s=>s.rapid.writes.filter(w=>w.key==='hp12c-state').length),historyWrites:selected.map(s=>s.rapid.writes.filter(w=>w.key==='hp12c-history-v1').length)})}
 results.push({name,version:await browser.version(),summary,samples});await fs.writeFile(new URL('performance.json',import.meta.url),JSON.stringify(results,null,2));console.log(JSON.stringify({name,summary},null,2));await browser.close();
}
