import {createRequire} from 'node:module';import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/mrpir/AppData/Local/Temp/hp12c-perf-tools/node_modules/playwright');
const browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_PATH||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'}),results=[];
for(const base of process.argv.slice(2)){
 const context=await browser.newContext({viewport:{width:402,height:874}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(String(e)));
 await context.addInitScript(()=>{if(!localStorage.getItem('hp12c-history-v1'))localStorage.setItem('hp12c-history-v1',JSON.stringify(Array.from({length:100},(_,i)=>({id:'release'+i,time:'2026-10-06T12:00:00Z',operation:'2 + 3',display:'5',value:5,...(i===99?{note:'Nota local preservada'}:{})}))))});
 const response=await page.goto(base);assert.equal(response.status(),200);await page.waitForFunction(()=>document.querySelector('.calculator')?.classList.contains('joined-frame'));await page.evaluate(()=>document.fonts.ready);
 const script=await page.locator('script[type="module"]').getAttribute('src'),bundleUrl=new URL(script,base).href,bundle=await page.request.get(bundleUrl);assert.equal(bundle.status(),200);assert.ok((await bundle.text()).includes('0.2.49'));
 const css=await page.locator('link[rel="stylesheet"]').first().getAttribute('href'),cssResponse=await page.request.get(new URL(css,base).href);assert.equal(cssResponse.status(),200);const sw=await page.request.get(new URL('sw.js',base).href);assert.equal(sw.status(),200);assert.ok(!(await sw.text()).includes('memory-board-photo.jpeg'));
 const saved=()=>page.evaluate(()=>({state:localStorage.getItem('hp12c-state'),history:localStorage.getItem('hp12c-history-v1')}));await page.waitForFunction(()=>localStorage.getItem('hp12c-state'));const initial=await saved();
 const drag=async(selector,dy)=>{const r=await page.locator(selector).boundingBox(),x=r.x+r.width/2,y=r.y+r.height/2;await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(x,y+dy,{steps:6});await page.mouse.up()};
 for(const selector of ['.silver-panel','.key-7','.lcd']){await drag(selector,90);await page.waitForTimeout(180);assert.equal(await page.locator('.history-board').count(),0);assert.deepEqual(await saved(),initial)}
 await page.locator('.brand').click();await page.locator('.history-board').waitFor();await page.waitForTimeout(250);assert.equal(await page.locator('.history-board .history-calculation-row').count(),100);assert.equal(await page.getByText('Nota local preservada',{exact:true}).count(),1);
 const background=await page.locator('.history-board').evaluate(el=>getComputedStyle(el).backgroundImage);assert.equal(background,'none');await drag('.history-board-heading',-90);await page.waitForTimeout(180);assert.equal(await page.locator('.history-board').count(),1);
 const screenshot=process.env.QA_SCREENSHOT_DIR?path.join(process.env.QA_SCREENSHOT_DIR,new URL(base).hostname+'-memory.png'):new URL(new URL(base).hostname+'-memory.png',import.meta.url).pathname.replace(/^\/(\w:)/,'$1');await page.screenshot({path:screenshot});
  await page.getByRole('button',{name:'Fechar memória',exact:true}).click();await page.locator('.history-board').waitFor({state:'detached'});assert.deepEqual(await saved(),initial);
 await page.waitForFunction(async()=>Boolean((await navigator.serviceWorker.getRegistration())?.active));await page.reload();await page.waitForFunction(()=>Boolean(navigator.serviceWorker.controller));await page.context().setOffline(true);await page.reload();await page.locator('.brand').waitFor();await page.locator('.brand').click();await page.locator('.history-board').waitFor();await page.getByRole('button',{name:'Fechar memória',exact:true}).click();await page.locator('.history-board').waitFor({state:'detached'});assert.deepEqual(await saved(),initial);assert.deepEqual(errors,[]);
 results.push({url:base,version:'0.2.49',html:response.status(),bundle:bundleUrl,css:cssResponse.status(),serviceWorker:sw.status(),calculatorPullDisabled:true,hpButtonOpensMemory:true,memoryPullDoesNotClose:true,topXClosesMemory:true,memorySettingsButtonRemoved:true,rows100:true,notesAndFinancialStatePreserved:true,offlineReload:true,errors});await context.close();
}
await browser.close();await fs.writeFile(process.env.QA_OUTPUT||new URL('release-results.json',import.meta.url),JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2));
